"""用户 / 会话 / 登录尝试的存储。

跟着项目既有惯例走：Store 类自带 `_SCHEMA`，构造时幂等建表（见 storage.py / marketstore.py）。
三张表落在主库 `fanisl`，与对话表同一个连接池。

几个不是随手定的设计：

- **会话 token 只存 sha256**。库被拖走时，攻击者拿到的是散列，不能直接当 cookie 用。
  token 本身只在响应头里出现一次。
- **用户名大小写不敏感**：统一小写存与查。"Alice" 和 "alice" 是同一个人，否则会出现
  两个看起来一样的账号。不引入 citext 扩展，规范化在应用层做。
- **改口令 / 停用 / 改角色都连带杀掉该用户的全部会话**。否则一个被停用的账号，
  手里那张 cookie 还能继续用到过期为止。
- **last_seen 节流写**：每个请求都 UPDATE 会话行的话，读接口会被写放大拖累。
  超过 5 分钟才写一次，闲置判定的精度因此是 5 分钟——对 14 天的闲置窗口足够。
"""

from __future__ import annotations

import hashlib
import secrets
from datetime import datetime, timedelta, timezone

from psycopg_pool import ConnectionPool

_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'member',
    display_name  TEXT NOT NULL DEFAULT '',
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS sessions (
    token_sha256 TEXT PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ NOT NULL,
    user_agent   TEXT NOT NULL DEFAULT '',
    ip           TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS login_attempts (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    ip       TEXT NOT NULL DEFAULT '',
    ok       BOOLEAN NOT NULL,
    at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_login_attempts_at ON login_attempts(at DESC);
"""

ROLES = ("admin", "member")

# 会话行里不含口令散列，但也别顺手 SELECT *：新增字段时不会悄悄漏进 API 响应
_USER_COLS = ("id, username, role, display_name, is_active, "
              "created_at, updated_at, last_login_at")

# last_seen 的节流阈值
_TOUCH_AFTER = timedelta(minutes=5)


def normalize_username(username: str) -> str:
    return username.strip().lower()


def _sha256(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def _now() -> datetime:
    return datetime.now(timezone.utc)


class UserExists(Exception):
    """用户名已被占用。"""


class UserStore:
    def __init__(self, pool: ConnectionPool) -> None:
        self.pool = pool
        self.init_db()

    def init_db(self) -> None:
        with self.pool.connection() as conn:
            conn.execute(_SCHEMA)

    # --- 用户 -------------------------------------------------------------

    def create_user(self, username: str, password_hash: str, *,
                    role: str = "member", display_name: str = "") -> dict:
        name = normalize_username(username)
        if role not in ROLES:
            raise ValueError(f"未知角色: {role}")
        with self.pool.connection() as conn:
            exists = conn.execute(
                "SELECT 1 FROM users WHERE username = %s", (name,)).fetchone()
            if exists:
                raise UserExists(name)
            return conn.execute(
                f"INSERT INTO users(username, password_hash, role, display_name) "
                f"VALUES (%s,%s,%s,%s) RETURNING {_USER_COLS}",
                (name, password_hash, role, display_name or name),
            ).fetchone()

    def get_by_username(self, username: str) -> dict | None:
        """含 password_hash——只给登录路径用，不要直接回给客户端。"""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT {_USER_COLS}, password_hash FROM users WHERE username = %s",
                (normalize_username(username),),
            ).fetchone()

    def get(self, user_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT {_USER_COLS} FROM users WHERE id = %s", (user_id,)).fetchone()

    def list_users(self) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT {_USER_COLS} FROM users ORDER BY id").fetchall()

    def count_active_admins(self) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT count(*) AS n FROM users WHERE role='admin' AND is_active"
            ).fetchone()
            return int(row["n"])

    def set_password(self, user_id: int, password_hash: str, *,
                     revoke_sessions: bool = True) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE users SET password_hash = %s, updated_at = now() WHERE id = %s",
                (password_hash, user_id))
            if revoke_sessions:
                conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))

    def set_active(self, user_id: int, active: bool) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE users SET is_active = %s, updated_at = now() WHERE id = %s",
                (active, user_id))
            if not active:
                conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))

    def set_display_name(self, user_id: int, display_name: str) -> None:
        # 显示名不影响权限，改它不必踢会话
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE users SET display_name = %s, updated_at = now() WHERE id = %s",
                (display_name, user_id))

    def set_role(self, user_id: int, role: str) -> None:
        if role not in ROLES:
            raise ValueError(f"未知角色: {role}")
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE users SET role = %s, updated_at = now() WHERE id = %s",
                (role, user_id))
            # 角色变了，旧会话里缓存的权限判断就不作数了——一律重登
            conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))

    def delete_user(self, user_id: int) -> None:
        with self.pool.connection() as conn:
            conn.execute("DELETE FROM users WHERE id = %s", (user_id,))

    def mark_login(self, user_id: int) -> None:
        with self.pool.connection() as conn:
            conn.execute("UPDATE users SET last_login_at = now() WHERE id = %s", (user_id,))

    # --- 会话 -------------------------------------------------------------

    def create_session(self, user_id: int, *, ttl: timedelta,
                       user_agent: str = "", ip: str = "") -> str:
        """返回明文 token（只在这一刻存在，库里存的是它的 sha256）。"""
        token = secrets.token_urlsafe(32)
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO sessions(token_sha256, user_id, expires_at, user_agent, ip) "
                "VALUES (%s,%s,%s,%s,%s)",
                (_sha256(token), user_id, _now() + ttl, user_agent[:300], ip[:64]),
            )
        return token

    def resolve_session(self, token: str, *, idle_ttl: timedelta) -> dict | None:
        """token → 用户行；过期 / 闲置超时 / 用户被停用一律返回 None。"""
        if not token:
            return None
        digest = _sha256(token)
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT s.expires_at, s.last_seen_at, "
                "       u.id, u.username, u.role, u.display_name, u.is_active, "
                "       u.created_at, u.updated_at, u.last_login_at "
                "FROM sessions s JOIN users u ON u.id = s.user_id "
                "WHERE s.token_sha256 = %s",
                (digest,),
            ).fetchone()
            if row is None:
                return None
            now = _now()
            if row["expires_at"] <= now or not row["is_active"]:
                conn.execute("DELETE FROM sessions WHERE token_sha256 = %s", (digest,))
                return None
            if now - row["last_seen_at"] > idle_ttl:
                conn.execute("DELETE FROM sessions WHERE token_sha256 = %s", (digest,))
                return None
            if now - row["last_seen_at"] > _TOUCH_AFTER:
                conn.execute(
                    "UPDATE sessions SET last_seen_at = now() WHERE token_sha256 = %s",
                    (digest,))
        return {k: row[k] for k in ("id", "username", "role", "display_name",
                                    "is_active", "created_at", "updated_at", "last_login_at")}

    def delete_session(self, token: str) -> None:
        with self.pool.connection() as conn:
            conn.execute("DELETE FROM sessions WHERE token_sha256 = %s", (_sha256(token),))

    def delete_user_sessions(self, user_id: int) -> int:
        with self.pool.connection() as conn:
            cur = conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))
            return cur.rowcount

    def list_sessions(self, user_id: int, current_token: str = "") -> list[dict]:
        """当前这条要标出来：几台设备的出口 IP 往往是同一个（都走一层 nginx），
        列表里只有 IP 和时间的话，人分不出哪一条是自己正在用的。
        比较放在 SQL 里做，token 的哈希不出这个方法。"""
        digest = _sha256(current_token) if current_token else ""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT created_at, last_seen_at, expires_at, user_agent, ip, "
                "       (token_sha256 = %s) AS is_current "
                "FROM sessions WHERE user_id = %s ORDER BY last_seen_at DESC",
                (digest, user_id)).fetchall()

    def purge_expired(self) -> int:
        with self.pool.connection() as conn:
            cur = conn.execute("DELETE FROM sessions WHERE expires_at <= now()")
            return cur.rowcount

    # --- 登录限速 ---------------------------------------------------------

    def record_attempt(self, username: str, ip: str, ok: bool) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO login_attempts(username, ip, ok) VALUES (%s,%s,%s)",
                (normalize_username(username)[:100], ip[:64], ok))

    def recent_failures(self, username: str, ip: str, window: timedelta) -> tuple[int, int]:
        """(该用户名的失败数, 该 IP 的失败数)，都只数窗口内、且在最近一次成功之后的。

        「最近一次成功之后」这一条很重要：不这么算的话，一个正常用户白天输错几次、
        晚上再登就可能被自己的历史挡在门外。
        """
        since = _now() - window
        name = normalize_username(username)
        with self.pool.connection() as conn:
            row = conn.execute(
                """
                SELECT
                  (SELECT count(*) FROM login_attempts a
                     WHERE a.username = %(u)s AND NOT a.ok AND a.at >= %(since)s
                       AND a.at > COALESCE(
                           (SELECT max(b.at) FROM login_attempts b
                             WHERE b.username = %(u)s AND b.ok AND b.at >= %(since)s),
                           '-infinity'::timestamptz)) AS by_user,
                  (SELECT count(*) FROM login_attempts a
                     WHERE a.ip = %(ip)s AND NOT a.ok AND a.at >= %(since)s
                       AND a.at > COALESCE(
                           (SELECT max(b.at) FROM login_attempts b
                             WHERE b.ip = %(ip)s AND b.ok AND b.at >= %(since)s),
                           '-infinity'::timestamptz)) AS by_ip
                """,
                {"u": name, "ip": ip[:64], "since": since},
            ).fetchone()
        return int(row["by_user"]), int(row["by_ip"])

    def housekeeping(self, *, attempts_keep_days: int = 30) -> dict:
        """日常清理：删过期会话与陈旧的登录尝试。由 collector 每天调一次。

        登录端点是公网可达的，`login_attempts` 会一直长。限速本身已经把增速卡住
        （被限速拒绝的那些不落库），但没有上限终究是个隐患。
        """
        return {
            "sessions": self.purge_expired(),
            "attempts": self.purge_attempts(timedelta(days=attempts_keep_days)),
        }

    def purge_attempts(self, older_than: timedelta) -> int:
        with self.pool.connection() as conn:
            cur = conn.execute(
                "DELETE FROM login_attempts WHERE at < %s", (_now() - older_than,))
            return cur.rowcount
