"""市场数据持久化（PostgreSQL + TimescaleDB）：
时间序列(metric_samples，hypertable) + 催化剂列表(catalyst_items) + 采集日志(collection_runs)。

与对话存储 storage.py 共用同一连接池、同一库（不同表，不同关注点）。
保留/压缩交给 TimescaleDB 原生策略（压缩 ~10x + 自动 drop_chunks），不再手写 compact。
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from psycopg_pool import ConnectionPool

GLOBAL = "GLOBAL"  # scope=global 的 symbol 占位

_SCHEMA = """
CREATE TABLE IF NOT EXISTS metric_samples (
    scope   TEXT NOT NULL,
    symbol  TEXT NOT NULL,
    metric  TEXT NOT NULL,
    ts      TIMESTAMPTZ NOT NULL,
    value   DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (scope, symbol, metric, ts)
);
CREATE INDEX IF NOT EXISTS idx_samples_q ON metric_samples(symbol, metric, ts);

CREATE TABLE IF NOT EXISTS catalyst_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        TEXT NOT NULL,
    symbol      TEXT NOT NULL,
    event_date  TEXT,
    title       TEXT NOT NULL,
    payload_json TEXT,
    fetched_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_catalyst_q ON catalyst_items(kind, symbol);

CREATE TABLE IF NOT EXISTS collection_runs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job        TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ok         INTEGER NOT NULL,
    note       TEXT
);
"""


@dataclass
class Sample:
    scope: str
    symbol: str
    metric: str
    value: float


def _differs(old: float | None, new: float) -> bool:
    """新值是否与上一条不同（含相对容差，避免浮点抖动当成变化）。"""
    if old is None:
        return True
    return abs(old - new) > max(1e-9, abs(old) * 1e-9)


def _iso(ts) -> str:
    """timestamptz → ISO 字符串（给 JSON 消费方，保持与旧接口一致）。"""
    return ts.isoformat() if hasattr(ts, "isoformat") else str(ts)


class MarketStore:
    def __init__(
        self,
        pool: ConnectionPool,
        *,
        retention_days: int = 365,
        compress_after_days: int = 7,
        runs_keep: int = 500,
    ) -> None:
        self.pool = pool
        self.retention_days = retention_days
        self.compress_after_days = compress_after_days
        self.runs_keep = runs_keep
        self.init_db()

    def init_db(self) -> None:
        with self.pool.connection() as conn:
            conn.execute(_SCHEMA)
            self._ensure_timescale(conn)

    def _ensure_timescale(self, conn) -> None:
        """把 metric_samples 变 hypertable + 配压缩 + 注册 retention 策略（全幂等）。"""
        conn.execute(
            "SELECT create_hypertable('metric_samples', 'ts', "
            "chunk_time_interval => interval '7 days', if_not_exists => TRUE)"
        )
        row = conn.execute(
            "SELECT compression_enabled FROM timescaledb_information.hypertables "
            "WHERE hypertable_name = 'metric_samples'"
        ).fetchone()
        if row is not None and not row["compression_enabled"]:
            conn.execute(
                "ALTER TABLE metric_samples SET ("
                " timescaledb.compress,"
                " timescaledb.compress_segmentby = 'scope, symbol, metric',"
                " timescaledb.compress_orderby = 'ts DESC')"
            )
        conn.execute(
            "SELECT add_compression_policy('metric_samples', "
            "compress_after => make_interval(days => %s), if_not_exists => TRUE)",
            (self.compress_after_days,),
        )
        conn.execute(
            "SELECT add_retention_policy('metric_samples', "
            "drop_after => make_interval(days => %s), if_not_exists => TRUE)",
            (self.retention_days,),
        )

    # --- 时间序列 --------------------------------------------------------

    def write_samples(self, samples: list[Sample], ts) -> int:
        """批量 upsert 样本（同 (scope,symbol,metric,ts) 重复则覆盖）。返回写入条数。"""
        if not samples:
            return 0
        rows = [(s.scope, s.symbol, s.metric, ts, float(s.value)) for s in samples]
        with self.pool.connection() as conn, conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO metric_samples(scope, symbol, metric, ts, value) "
                "VALUES (%s,%s,%s,%s,%s) "
                "ON CONFLICT (scope, symbol, metric, ts) DO UPDATE SET value = EXCLUDED.value",
                rows,
            )
        return len(rows)

    def write_changed(self, samples: list[Sample], ts) -> int:
        """只写「与该指标最近一条值不同」的样本——让各指标按自身变化节奏落库。

        慢变量(稳定币/链TVL/恐惧贪婪/日线指标)日内不变 → 不重复写；价格等每周期都变 → 照写。
        """
        if not samples:
            return 0
        last: dict[tuple[str, str], float] = {}
        for symbol in {s.symbol for s in samples}:
            for metric, info in self.latest_metrics(symbol).items():
                last[(symbol, metric)] = info["value"]
        changed = [s for s in samples if _differs(last.get((s.symbol, s.metric)), s.value)]
        return self.write_samples(changed, ts)

    def get_series(self, symbol: str, metrics: list[str], since=None) -> dict[str, list[dict]]:
        """取 {metric: [{ts, value}...]}（按时间升序）。"""
        if not metrics:
            return {}
        out: dict[str, list[dict]] = {m: [] for m in metrics}
        sql = (
            "SELECT metric, ts, value FROM metric_samples "
            "WHERE symbol = %s AND metric = ANY(%s)"
        )
        params: list = [symbol, metrics]
        if since:
            sql += " AND ts >= %s::timestamptz"
            params.append(since)
        sql += " ORDER BY ts ASC"
        with self.pool.connection() as conn:
            for r in conn.execute(sql, params).fetchall():
                out[r["metric"]].append({"ts": _iso(r["ts"]), "value": r["value"]})
        return out

    def latest_metrics(self, symbol: str) -> dict[str, dict]:
        """某 symbol 每个 metric 的最新一条 {metric: {ts, value}}。"""
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT DISTINCT ON (metric) metric, ts, value FROM metric_samples "
                "WHERE symbol = %s ORDER BY metric, ts DESC",
                (symbol,),
            ).fetchall()
        return {r["metric"]: {"ts": _iso(r["ts"]), "value": r["value"]} for r in rows}

    # --- 催化剂列表 ------------------------------------------------------

    def replace_catalysts(self, kind: str, symbol: str, items: list[dict]) -> int:
        """先删 (kind, symbol) 的旧记录再插新 = 最新快照语义。"""
        with self.pool.connection() as conn, conn.cursor() as cur:
            cur.execute(
                "DELETE FROM catalyst_items WHERE kind = %s AND symbol = %s", (kind, symbol)
            )
            cur.executemany(
                "INSERT INTO catalyst_items(kind, symbol, event_date, title, payload_json) "
                "VALUES (%s,%s,%s,%s,%s)",
                [
                    (
                        kind,
                        symbol,
                        it.get("event_date"),
                        it.get("title") or "",
                        json.dumps(it.get("payload"), ensure_ascii=False)
                        if it.get("payload") is not None
                        else None,
                    )
                    for it in items
                ],
            )
        return len(items)

    def get_catalysts(self, symbol: str | None = None) -> list[dict]:
        with self.pool.connection() as conn:
            if symbol:
                rows = conn.execute(
                    "SELECT kind, symbol, event_date, title, payload_json, fetched_at "
                    "FROM catalyst_items WHERE symbol = ANY(%s) ORDER BY event_date ASC",
                    ([symbol, GLOBAL],),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT kind, symbol, event_date, title, payload_json, fetched_at "
                    "FROM catalyst_items ORDER BY event_date ASC"
                ).fetchall()
        out = []
        for r in rows:
            payload_json = r.pop("payload_json")
            r["payload"] = json.loads(payload_json) if payload_json else None
            out.append(r)
        return out

    # --- 采集日志 --------------------------------------------------------

    def log_run(self, job: str, ok: bool, note: str = "") -> None:
        with self.pool.connection() as conn, conn.cursor() as cur:
            cur.execute(
                "INSERT INTO collection_runs(job, ok, note) VALUES (%s,%s,%s)",
                (job, 1 if ok else 0, note),
            )
            # 顺带裁剪日志，控制行数（单用户量很小，单条 DELETE 足够）
            cur.execute(
                "DELETE FROM collection_runs WHERE id NOT IN "
                "(SELECT id FROM collection_runs ORDER BY id DESC LIMIT %s)",
                (self.runs_keep,),
            )

    def status(self) -> list[dict]:
        """每个 job 的最近一次运行。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT DISTINCT ON (job) job, started_at, ok, note "
                "FROM collection_runs ORDER BY job, id DESC"
            ).fetchall()
