"""市场数据持久化（PostgreSQL + TimescaleDB）：
时间序列(metric_samples，hypertable) + 催化剂列表(catalyst_items) + 采集日志(collection_runs)。

与对话存储 storage.py 共用同一连接池、同一库（不同表，不同关注点）。
保留/压缩交给 TimescaleDB 原生策略（压缩 ~10x + 自动 drop_chunks），不再手写 compact。
"""

from __future__ import annotations

import logging

import psycopg

import json
from dataclasses import dataclass

from psycopg_pool import ConnectionPool

log = logging.getLogger("analyzer.marketstore")

GLOBAL = "GLOBAL"  # scope=global 的 symbol 占位

_SCHEMA = """
CREATE TABLE IF NOT EXISTS metric_samples (
    scope   TEXT NOT NULL,
    symbol  TEXT NOT NULL,
    metric  TEXT NOT NULL,
    ts      TIMESTAMPTZ NOT NULL,
    value   DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (scope, symbol, metric, ts)
);
CREATE INDEX IF NOT EXISTS idx_samples_q ON metric_samples(symbol, metric, ts);

CREATE TABLE IF NOT EXISTS catalyst_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        TEXT NOT NULL,
    symbol      TEXT NOT NULL,
    event_date  TEXT,
    title       TEXT NOT NULL,
    payload_json TEXT,
    fetched_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_catalyst_q ON catalyst_items(kind, symbol);

CREATE TABLE IF NOT EXISTS collection_runs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job        TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ok         INTEGER NOT NULL,
    note       TEXT
);
"""


@dataclass
class Sample:
    scope: str
    symbol: str
    metric: str
    value: float


def _differs(old: float | None, new: float) -> bool:
    """新值是否与上一条不同（含相对容差，避免浮点抖动当成变化）。"""
    if old is None:
        return True
    return abs(old - new) > max(1e-9, abs(old) * 1e-9)


def _iso(ts) -> str:
    """timestamptz → ISO 字符串（给 JSON 消费方，保持与旧接口一致）。"""
    return ts.isoformat() if hasattr(ts, "isoformat") else str(ts)


class MarketStore:
    def __init__(
        self,
        pool: ConnectionPool,
        *,
        retention_days: int = 0,
        compress_after_days: int = 7,
        runs_keep: int = 500,
    ) -> None:
        self.pool = pool
        self.retention_days = retention_days
        self.compress_after_days = compress_after_days
        self.runs_keep = runs_keep
        self.init_db()

    def init_db(self) -> None:
        with self.pool.connection() as conn:
            conn.execute(_SCHEMA)
        # **必须另开一个事务**：扩展缺失时 create_hypertable 报错会中止当前事务，
        # 与建表放在一起的话，捕获异常也救不回来——_SCHEMA 建的表会被一并回滚，
        # 后续报的是 relation "collection_runs" does not exist，与真正的原因隔了一层。
        try:
            with self.pool.connection() as conn:
                self._ensure_timescale(conn)
        except psycopg.errors.UndefinedFunction:
                # 扩展没装：metric_samples 退化成普通表，读写照常，只是没有分块与压缩。
                # 不能让它硬崩——runtime 在模块级就构造 MarketStore，崩了会连带
                # 整个 app（以及只想用一个纯函数的测试）都起不来。
                # 服务器上扩展是装了的，这条分支只影响开发机与全新环境。
                log.warning("metric_samples 未启用 timescaledb（扩展不可用），"
                            "按普通表运行：无分块、无压缩、无 retention 策略")

    def _ensure_timescale(self, conn) -> None:
        """把 metric_samples 变 hypertable + 配压缩 + 注册 retention 策略（全幂等）。"""
        conn.execute(
            "SELECT create_hypertable('metric_samples', 'ts', "
            "chunk_time_interval => interval '7 days', if_not_exists => TRUE)"
        )
        row = conn.execute(
            "SELECT compression_enabled FROM timescaledb_information.hypertables "
            "WHERE hypertable_name = 'metric_samples'"
        ).fetchone()
        if row is not None and not row["compression_enabled"]:
            conn.execute(
                "ALTER TABLE metric_samples SET ("
                " timescaledb.compress,"
                " timescaledb.compress_segmentby = 'scope, symbol, metric',"
                " timescaledb.compress_orderby = 'ts DESC')"
            )
        conn.execute(
            "SELECT add_compression_policy('metric_samples', "
            "compress_after => make_interval(days => %s), if_not_exists => TRUE)",
            (self.compress_after_days,),
        )
        if self.retention_days > 0:
            conn.execute(
                "SELECT add_retention_policy('metric_samples', "
                "drop_after => make_interval(days => %s), if_not_exists => TRUE)",
                (self.retention_days,),
            )
        else:
            # 研究平台需要永久历史：retention=0 时不注册，且**主动移除**历史上注册过的策略
            # （365 天策略曾整体吃掉 2006+ 深回填——2026-07 事故）。
            conn.execute(
                "SELECT remove_retention_policy('metric_samples', if_exists => TRUE)"
            )

    # --- 时间序列 --------------------------------------------------------

    def write_samples(self, samples: list[Sample], ts) -> int:
        """批量 upsert 样本（同 (scope,symbol,metric,ts) 重复则覆盖）。返回写入条数。"""
        if not samples:
            return 0
        rows = [(s.scope, s.symbol, s.metric, ts, float(s.value)) for s in samples]
        with self.pool.connection() as conn, conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO metric_samples(scope, symbol, metric, ts, value) "
                "VALUES (%s,%s,%s,%s,%s) "
                "ON CONFLICT (scope, symbol, metric, ts) DO UPDATE SET value = EXCLUDED.value",
                rows,
            )
        return len(rows)

    def write_history(self, rows: list[tuple]) -> int:
        """回填用：批量写「自带时间戳」的历史样本。rows=[(scope,symbol,metric,ts,value)...]。

        与 write_samples 的区别：每行各自的 ts（一次回填跨成百上千根 K 线），分块 executemany。
        ON CONFLICT 覆盖，整条命令可重复跑（幂等）。
        """
        if not rows:
            return 0
        norm = [(s, sym, m, ts, float(v)) for (s, sym, m, ts, v) in rows]
        with self.pool.connection() as conn, conn.cursor() as cur:
            for i in range(0, len(norm), 5000):
                cur.executemany(
                    "INSERT INTO metric_samples(scope, symbol, metric, ts, value) "
                    "VALUES (%s,%s,%s,%s,%s) "
                    "ON CONFLICT (scope, symbol, metric, ts) DO UPDATE SET value = EXCLUDED.value",
                    norm[i : i + 5000],
                )
        return len(norm)

    def write_changed(self, samples: list[Sample], ts) -> int:
        """只写「与该指标最近一条值不同」的样本——让各指标按自身变化节奏落库。

        慢变量(稳定币/链TVL/恐惧贪婪/日线指标)日内不变 → 不重复写；价格等每周期都变 → 照写。
        """
        if not samples:
            return 0
        last: dict[tuple[str, str], float] = {}
        for symbol in {s.symbol for s in samples}:
            for metric, info in self.latest_metrics(symbol).items():
                last[(symbol, metric)] = info["value"]
        changed = [s for s in samples if _differs(last.get((s.symbol, s.metric)), s.value)]
        return self.write_samples(changed, ts)

    def get_series(self, symbol: str, metrics: list[str], since=None) -> dict[str, list[dict]]:
        """取 {metric: [{ts, value}...]}（按时间升序）。"""
        if not metrics:
            return {}
        out: dict[str, list[dict]] = {m: [] for m in metrics}
        sql = (
            "SELECT metric, ts, value FROM metric_samples "
            "WHERE symbol = %s AND metric = ANY(%s)"
        )
        params: list = [symbol, metrics]
        if since:
            sql += " AND ts >= %s::timestamptz"
            params.append(since)
        sql += " ORDER BY ts ASC"
        with self.pool.connection() as conn:
            for r in conn.execute(sql, params).fetchall():
                out[r["metric"]].append({"ts": _iso(r["ts"]), "value": r["value"]})
        return out

    def metric_coverage(self, symbol: str) -> list[dict]:
        """某 symbol 各 metric 的覆盖情况：{metric, samples, first_ts, last_ts, last_value}。

        给前端数据浏览器用——知道哪些指标有数据、历史多深。
        """
        sql = (
            "SELECT metric, count(*) AS samples, min(ts) AS first_ts, max(ts) AS last_ts, "
            "(array_agg(value ORDER BY ts DESC))[1] AS last_value "
            "FROM metric_samples WHERE symbol=%s GROUP BY metric ORDER BY metric"
        )
        with self.pool.connection() as conn:
            rows = conn.execute(sql, (symbol,)).fetchall()
        return [
            {"metric": r["metric"], "samples": r["samples"],
             "first_ts": _iso(r["first_ts"]), "last_ts": _iso(r["last_ts"]),
             "last_value": r["last_value"]}
            for r in rows
        ]

    def latest_metrics(self, symbol: str) -> dict[str, dict]:
        """某 symbol 每个 metric 的最新一条 {metric: {ts, value}}。"""
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT DISTINCT ON (metric) metric, ts, value FROM metric_samples "
                "WHERE symbol = %s ORDER BY metric, ts DESC",
                (symbol,),
            ).fetchall()
        return {r["metric"]: {"ts": _iso(r["ts"]), "value": r["value"]} for r in rows}

    # --- 催化剂列表 ------------------------------------------------------

    def replace_catalysts(self, kind: str, symbol: str, items: list[dict]) -> int:
        """先删 (kind, symbol) 的旧记录再插新 = 最新快照语义。"""
        with self.pool.connection() as conn, conn.cursor() as cur:
            cur.execute(
                "DELETE FROM catalyst_items WHERE kind = %s AND symbol = %s", (kind, symbol)
            )
            cur.executemany(
                "INSERT INTO catalyst_items(kind, symbol, event_date, title, payload_json) "
                "VALUES (%s,%s,%s,%s,%s)",
                [
                    (
                        kind,
                        symbol,
                        it.get("event_date"),
                        it.get("title") or "",
                        json.dumps(it.get("payload"), ensure_ascii=False)
                        if it.get("payload") is not None
                        else None,
                    )
                    for it in items
                ],
            )
        return len(items)

    def catalyst_coverage(self) -> list[dict]:
        """按 (kind, symbol) 的条目数与最近抓取时刻——标的页的"数据覆盖"用。

        不走 get_catalysts：那个会把全部 payload 一起拉回来，只为数个数不值当。
        """
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT kind, symbol, count(*) AS n, max(fetched_at) AS fetched_at "
                "FROM catalyst_items GROUP BY kind, symbol ORDER BY kind, symbol"
            ).fetchall()

    def get_catalysts(self, symbol: str | None = None) -> list[dict]:
        with self.pool.connection() as conn:
            if symbol:
                rows = conn.execute(
                    "SELECT kind, symbol, event_date, title, payload_json, fetched_at "
                    "FROM catalyst_items WHERE symbol = ANY(%s) ORDER BY event_date ASC",
                    ([symbol, GLOBAL],),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT kind, symbol, event_date, title, payload_json, fetched_at "
                    "FROM catalyst_items ORDER BY event_date ASC"
                ).fetchall()
        out = []
        for r in rows:
            payload_json = r.pop("payload_json")
            r["payload"] = json.loads(payload_json) if payload_json else None
            out.append(r)
        return out

    # --- 采集日志 --------------------------------------------------------

    def log_run(self, job: str, ok: bool, note: str = "") -> None:
        with self.pool.connection() as conn, conn.cursor() as cur:
            cur.execute(
                "INSERT INTO collection_runs(job, ok, note) VALUES (%s,%s,%s)",
                (job, 1 if ok else 0, note),
            )
            # 顺带裁剪日志，控制行数（单用户量很小，单条 DELETE 足够）
            cur.execute(
                "DELETE FROM collection_runs WHERE id NOT IN "
                "(SELECT id FROM collection_runs ORDER BY id DESC LIMIT %s)",
                (self.runs_keep,),
            )

    def status(self) -> list[dict]:
        """每个 job 的最近一次运行。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT DISTINCT ON (job) job, started_at, ok, note "
                "FROM collection_runs ORDER BY job, id DESC"
            ).fetchall()
