"""交易评测台持久化（PostgreSQL，独立库 fanisl_trading）。

账户/交易/版本化计划/只读决策输入/委托/持仓快照/事件时间线/客观结果/复盘。
引擎写客观数据，agent 写 Claude 的结构化产出；前端读 timeline()。账户级指标 scorecard() 现算。
"""

from __future__ import annotations

from contextlib import contextmanager
from typing import Any

from psycopg.types.json import Json
from psycopg_pool import ConnectionPool

# advisory lock 命名空间：把「容量检查 + 开仓」串行化到账户维度（防并发越过仓位/风险上限）
_LOCK_NS = 0x7A11

_SCHEMA = """
CREATE TABLE IF NOT EXISTS accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL UNIQUE,
    base_currency    TEXT NOT NULL DEFAULT 'USDT',
    initial_balance  DOUBLE PRECISION NOT NULL,
    balance          DOUBLE PRECISION NOT NULL,
    max_leverage     DOUBLE PRECISION NOT NULL,
    margin_mode      TEXT NOT NULL,
    default_risk_pct DOUBLE PRECISION NOT NULL,
    force_trade      BOOLEAN NOT NULL DEFAULT false,  -- 开启后 Claude 不能选择"不交易"
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trades (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    symbol            TEXT NOT NULL,
    side              TEXT NOT NULL,
    strategy_type     TEXT NOT NULL,
    leverage          DOUBLE PRECISION NOT NULL,
    status            TEXT NOT NULL,              -- planned|open|closed|cancelled
    qty               DOUBLE PRECISION NOT NULL DEFAULT 0,
    avg_entry         DOUBLE PRECISION,
    liquidation_price DOUBLE PRECISION,
    margin            DOUBLE PRECISION NOT NULL DEFAULT 0,
    opened_at         TIMESTAMPTZ,
    closed_at         TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_trades_acct ON trades(account_id, status);

CREATE TABLE IF NOT EXISTS trade_plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id    BIGINT NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
    version     INT NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    plan        JSONB NOT NULL,        -- TradePlan dump + 引擎算出的 qty/margin/rr/liq
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (trade_id, version)
);

CREATE TABLE IF NOT EXISTS decision_inputs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id     BIGINT NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
    plan_version INT,
    kind         TEXT NOT NULL,        -- entry|reeval|review
    inputs       JSONB,                -- 冻结：Claude 当时看到的数据
    prompt       TEXT,
    response     JSONB,                -- Claude 完整 content blocks
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id   BIGINT NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
    kind       TEXT NOT NULL,          -- entry|add|reduce|sl|tp|exit
    price      DOUBLE PRECISION NOT NULL,
    qty        DOUBLE PRECISION NOT NULL,
    fee        DOUBLE PRECISION NOT NULL DEFAULT 0,
    status     TEXT NOT NULL,          -- pending|filled|cancelled
    actor      TEXT NOT NULL,          -- engine|claude|user
    reason     TEXT,
    placed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    filled_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_orders_trade ON orders(trade_id);

CREATE TABLE IF NOT EXISTS position_snapshots (
    trade_id   BIGINT NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
    ts         TIMESTAMPTZ NOT NULL,
    mark       DOUBLE PRECISION NOT NULL,
    qty        DOUBLE PRECISION NOT NULL,
    avg_entry  DOUBLE PRECISION NOT NULL,
    margin     DOUBLE PRECISION NOT NULL,
    upnl       DOUBLE PRECISION NOT NULL,
    dist_sl    DOUBLE PRECISION,
    dist_tp    DOUBLE PRECISION,
    liq_price  DOUBLE PRECISION,
    holding_s  DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (trade_id, ts)
);

CREATE TABLE IF NOT EXISTS trade_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id   BIGINT NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
    ts         TIMESTAMPTZ NOT NULL DEFAULT now(),
    kind       TEXT NOT NULL,
    actor      TEXT NOT NULL,
    payload    JSONB
);
CREATE INDEX IF NOT EXISTS idx_events_trade ON trade_events(trade_id, ts);

CREATE TABLE IF NOT EXISTS trade_results (
    trade_id    BIGINT PRIMARY KEY REFERENCES trades(id) ON DELETE CASCADE,
    pnl_abs     DOUBLE PRECISION NOT NULL,
    pnl_pct     DOUBLE PRECISION NOT NULL,     -- 相对初始保证金
    realized_r  DOUBLE PRECISION,              -- 实际盈亏 / 计划风险额
    planned_r   DOUBLE PRECISION,              -- 计划盈亏比
    mfe_r       DOUBLE PRECISION,              -- 最大有利波动（R）
    mae_r       DOUBLE PRECISION,              -- 最大不利波动（R）
    exit_efficiency  DOUBLE PRECISION,         -- 实际R / MFE_R：吃到了多少有利波动
    counterfactual_r DOUBLE PRECISION,         -- 不管理基准（原SL/TP谁先到）
    mgmt_contribution_r DOUBLE PRECISION,      -- 管理层贡献 = 实际R − 反事实R
    holding_s   DOUBLE PRECISION NOT NULL,
    exit_reason TEXT NOT NULL,
    outcome     TEXT NOT NULL,                 -- win|loss|breakeven
    fees        DOUBLE PRECISION NOT NULL DEFAULT 0,
    closed_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trade_reviews (
    trade_id   BIGINT PRIMARY KEY REFERENCES trades(id) ON DELETE CASCADE,
    review     JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS declines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    symbol     TEXT NOT NULL,
    reason     TEXT NOT NULL,
    watch_for  TEXT,
    recheck_after_hours DOUBLE PRECISION,   -- 多久后值得重评（到期自动用行情校验拒绝对错）
    bias_if_forced      TEXT,               -- 若被强制会做哪边（long/short），用于评测拒绝判断
    recheck_outcome     JSONB,              -- 到期校验结果（引擎回填）
    inputs     JSONB,
    transcript JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""


def _iso(ts) -> Any:
    return ts.isoformat() if hasattr(ts, "isoformat") else ts


class TradingStore:
    def __init__(self, pool: ConnectionPool) -> None:
        self.pool = pool
        self.init_db()

    def init_db(self) -> None:
        with self.pool.connection() as conn:
            conn.execute(_SCHEMA)
            # 老库补列（CREATE TABLE IF NOT EXISTS 不会给已存在的表加列）
            conn.execute(
                "ALTER TABLE accounts ADD COLUMN IF NOT EXISTS "
                "force_trade BOOLEAN NOT NULL DEFAULT false"
            )
            for col, typ in [
                ("recheck_after_hours", "DOUBLE PRECISION"),
                ("bias_if_forced", "TEXT"),
                ("recheck_outcome", "JSONB"),
            ]:
                conn.execute(f"ALTER TABLE declines ADD COLUMN IF NOT EXISTS {col} {typ}")
            for col in ("mfe_r", "mae_r", "exit_efficiency", "counterfactual_r",
                        "mgmt_contribution_r"):
                conn.execute(f"ALTER TABLE trade_results ADD COLUMN IF NOT EXISTS {col} DOUBLE PRECISION")

    # --- 账户 -------------------------------------------------------------

    def ensure_account(
        self, name: str, *, initial_balance: float, max_leverage: float,
        margin_mode: str, default_risk_pct: float,
    ) -> dict:
        """按 name 取或建账户。新建时用给定条款；已存在但**还没交易过**则采用新条款
        （让 config 对空账户有权威性，又绝不改动已在跑的账户，免得损坏进行中的实验）。
        """
        with self.pool.connection() as conn:
            row = conn.execute("SELECT * FROM accounts WHERE name=%s", (name,)).fetchone()
            if row is None:
                return conn.execute(
                    "INSERT INTO accounts(name, initial_balance, balance, max_leverage, "
                    "margin_mode, default_risk_pct) VALUES (%s,%s,%s,%s,%s,%s) RETURNING *",
                    (name, initial_balance, initial_balance, max_leverage, margin_mode, default_risk_pct),
                ).fetchone()
            traded = conn.execute(
                "SELECT 1 FROM trades WHERE account_id=%s LIMIT 1", (row["id"],)
            ).fetchone()
            if traded is None and (
                row["margin_mode"] != margin_mode
                or row["initial_balance"] != initial_balance
                or row["max_leverage"] != max_leverage
            ):
                return conn.execute(
                    "UPDATE accounts SET initial_balance=%s, balance=%s, max_leverage=%s, "
                    "margin_mode=%s, default_risk_pct=%s WHERE id=%s RETURNING *",
                    (initial_balance, initial_balance, max_leverage, margin_mode, default_risk_pct, row["id"]),
                ).fetchone()
            return row

    def get_account(self, account_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute("SELECT * FROM accounts WHERE id=%s", (account_id,)).fetchone()

    def set_force_trade(self, account_id: int, enabled: bool) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE accounts SET force_trade=%s WHERE id=%s", (enabled, account_id)
            )

    def adjust_balance(self, account_id: int, delta: float) -> None:
        with self.pool.connection() as conn:
            conn.execute("UPDATE accounts SET balance = balance + %s WHERE id=%s", (delta, account_id))

    def used_margin(self, account_id: int) -> float:
        """账户当前被未平仓交易占用的保证金合计。"""
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT COALESCE(SUM(margin),0) AS m FROM trades "
                "WHERE account_id=%s AND status='open'",
                (account_id,),
            ).fetchone()
        return float(row["m"])

    @contextmanager
    def account_lock(self, account_id: int):
        """账户级 advisory 锁：把「容量检查 + 开仓」串行化，避免并发越过仓位/在险上限。

        只该包住快速的临界区（检查+建仓），**不要**把 Claude 决策放进来——那会长时间占用连接。
        """
        with self.pool.connection() as conn:
            conn.execute("SELECT pg_advisory_lock(%s, %s)", (_LOCK_NS, account_id))
            try:
                yield
            finally:
                conn.execute("SELECT pg_advisory_unlock(%s, %s)", (_LOCK_NS, account_id))

    def mirrored_source_ids(self, shadow_account_id: int) -> set[int]:
        """影子账户里已镜像过的源交易 id 集合（避免重复镜像）。"""
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT (e.payload->>'source_trade_id')::bigint AS src "
                "FROM trade_events e JOIN trades t ON t.id=e.trade_id "
                "WHERE t.account_id=%s AND e.kind='mirrored'",
                (shadow_account_id,),
            ).fetchall()
        return {int(r["src"]) for r in rows if r["src"] is not None}

    def committed_trades(self, account_id: int) -> list[dict]:
        """占用账户额度的交易：持仓中 + 挂着限价进场单的（都算已承诺）。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT DISTINCT t.* FROM trades t "
                "LEFT JOIN orders o ON o.trade_id=t.id AND o.kind='entry' AND o.status='pending' "
                "WHERE t.account_id=%s AND (t.status='open' OR o.id IS NOT NULL) ORDER BY t.id",
                (account_id,),
            ).fetchall()

    # --- 交易与计划 -------------------------------------------------------

    def create_trade(
        self, account_id: int, symbol: str, side: str, strategy_type: str, leverage: float,
    ) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO trades(account_id, symbol, side, strategy_type, leverage, status) "
                "VALUES (%s,%s,%s,%s,%s,'planned') RETURNING id",
                (account_id, symbol, side, strategy_type, leverage),
            ).fetchone()
        return int(row["id"])

    def add_plan(self, trade_id: int, plan: dict, *, version: int, make_active: bool = True) -> int:
        with self.pool.connection() as conn:
            if make_active:
                conn.execute("UPDATE trade_plans SET is_active=FALSE WHERE trade_id=%s", (trade_id,))
            row = conn.execute(
                "INSERT INTO trade_plans(trade_id, version, is_active, plan) "
                "VALUES (%s,%s,%s,%s) RETURNING id",
                (trade_id, version, make_active, Json(plan)),
            ).fetchone()
        return int(row["id"])

    def active_plan(self, trade_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM trade_plans WHERE trade_id=%s AND is_active ORDER BY version DESC LIMIT 1",
                (trade_id,),
            ).fetchone()

    def plan_versions(self, trade_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM trade_plans WHERE trade_id=%s ORDER BY version ASC", (trade_id,)
            ).fetchall()

    def next_plan_version(self, trade_id: int) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT COALESCE(MAX(version),0)+1 AS v FROM trade_plans WHERE trade_id=%s", (trade_id,)
            ).fetchone()
        return int(row["v"])

    def save_decision_inputs(
        self, trade_id: int, kind: str, *, plan_version: int | None = None,
        inputs: dict | None = None, prompt: str | None = None, response: Any = None,
    ) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO decision_inputs(trade_id, plan_version, kind, inputs, prompt, response) "
                "VALUES (%s,%s,%s,%s,%s,%s)",
                (trade_id, plan_version, kind,
                 Json(inputs) if inputs is not None else None, prompt,
                 Json(response) if response is not None else None),
            )

    # --- 仓位状态 ---------------------------------------------------------

    def open_position(
        self, trade_id: int, *, avg_entry: float, qty: float, margin: float, liq: float, opened_at,
    ) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE trades SET status='open', avg_entry=%s, qty=%s, margin=%s, "
                "liquidation_price=%s, opened_at=%s WHERE id=%s",
                (avg_entry, qty, margin, liq, opened_at, trade_id),
            )

    def update_position(
        self, trade_id: int, *, qty: float, avg_entry: float, margin: float, liq: float,
    ) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE trades SET qty=%s, avg_entry=%s, margin=%s, liquidation_price=%s WHERE id=%s",
                (qty, avg_entry, margin, liq, trade_id),
            )

    def close_position(self, trade_id: int, *, closed_at, status: str = "closed") -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE trades SET status=%s, qty=0, margin=0, closed_at=%s WHERE id=%s",
                (status, closed_at, trade_id),
            )

    def void_pending_entry(self, trade_id: int) -> None:
        """作废挂着的限价进场单（不动 trade 状态）——用于即将成交前清掉旧挂单。"""
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE orders SET status='cancelled' "
                "WHERE trade_id=%s AND kind='entry' AND status='pending'",
                (trade_id,),
            )

    def cancel_pending_entry(self, trade_id: int, *, reason: str = "撤单") -> bool:
        """撤掉限价进场挂单并把 planned 交易置为 cancelled。返回是否确有挂单被撤。"""
        with self.pool.connection() as conn:
            n = conn.execute(
                "UPDATE orders SET status='cancelled', reason=%s "
                "WHERE trade_id=%s AND kind='entry' AND status='pending'",
                (reason, trade_id),
            ).rowcount
            conn.execute(
                "UPDATE trades SET status='cancelled' WHERE id=%s AND status='planned'",
                (trade_id,),
            )
        return n > 0

    def get_trade(self, trade_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute("SELECT * FROM trades WHERE id=%s", (trade_id,)).fetchone()

    def list_trades(self, account_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT t.*, r.pnl_abs, r.pnl_pct, r.realized_r, r.outcome, r.exit_reason, "
                "r.holding_s, rv.review->>'skill_vs_luck' AS skill_vs_luck "
                "FROM trades t "
                "LEFT JOIN trade_results r ON r.trade_id = t.id "
                "LEFT JOIN trade_reviews rv ON rv.trade_id = t.id "
                "WHERE t.account_id=%s ORDER BY t.id DESC",
                (account_id,),
            ).fetchall()

    def list_open_trades(self, account_id: int | None = None) -> list[dict]:
        with self.pool.connection() as conn:
            if account_id is None:
                return conn.execute("SELECT * FROM trades WHERE status='open' ORDER BY id").fetchall()
            return conn.execute(
                "SELECT * FROM trades WHERE status='open' AND account_id=%s ORDER BY id", (account_id,)
            ).fetchall()

    # --- 委托 / 快照 / 事件 ----------------------------------------------

    def add_order(
        self, trade_id: int, *, kind: str, price: float, qty: float, fee: float,
        actor: str, status: str = "filled", reason: str | None = None,
        filled_at=None, placed_at=None,
    ) -> int:
        # placed_at 显式传引擎时钟（保持与盯市/TTL 同一时间基准）；不传则用 DB now()
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO orders(trade_id, kind, price, qty, fee, status, actor, reason, "
                "filled_at, placed_at) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,COALESCE(%s, now())) "
                "RETURNING id",
                (trade_id, kind, price, qty, fee, status, actor, reason, filled_at, placed_at),
            ).fetchone()
        return int(row["id"])

    def orders(self, trade_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM orders WHERE trade_id=%s ORDER BY id", (trade_id,)
            ).fetchall()

    def write_position_snapshot(self, trade_id: int, ts, **fields) -> None:
        cols = ["mark", "qty", "avg_entry", "margin", "upnl", "dist_sl", "dist_tp", "liq_price", "holding_s"]
        vals = [fields.get(c) for c in cols]
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO position_snapshots(trade_id, ts, mark, qty, avg_entry, margin, upnl, "
                "dist_sl, dist_tp, liq_price, holding_s) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) "
                "ON CONFLICT (trade_id, ts) DO NOTHING",
                (trade_id, ts, *vals),
            )

    def position_snapshots(self, trade_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM position_snapshots WHERE trade_id=%s ORDER BY ts", (trade_id,)
            ).fetchall()

    def latest_position_snapshot(self, trade_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM position_snapshots WHERE trade_id=%s ORDER BY ts DESC LIMIT 1",
                (trade_id,),
            ).fetchone()

    def add_event(self, trade_id: int, kind: str, actor: str, payload: dict | None = None) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO trade_events(trade_id, kind, actor, payload) VALUES (%s,%s,%s,%s)",
                (trade_id, kind, actor, Json(payload) if payload is not None else None),
            )

    def events(self, trade_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM trade_events WHERE trade_id=%s ORDER BY ts, id", (trade_id,)
            ).fetchall()

    # --- 结果 / 复盘 ------------------------------------------------------

    def save_result(self, trade_id: int, **f) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO trade_results(trade_id, pnl_abs, pnl_pct, realized_r, planned_r, "
                "mfe_r, mae_r, exit_efficiency, counterfactual_r, mgmt_contribution_r, "
                "holding_s, exit_reason, outcome, fees) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) "
                "ON CONFLICT (trade_id) DO UPDATE SET pnl_abs=EXCLUDED.pnl_abs, pnl_pct=EXCLUDED.pnl_pct, "
                "realized_r=EXCLUDED.realized_r, planned_r=EXCLUDED.planned_r, mfe_r=EXCLUDED.mfe_r, "
                "mae_r=EXCLUDED.mae_r, exit_efficiency=EXCLUDED.exit_efficiency, "
                "counterfactual_r=EXCLUDED.counterfactual_r, mgmt_contribution_r=EXCLUDED.mgmt_contribution_r, "
                "holding_s=EXCLUDED.holding_s, exit_reason=EXCLUDED.exit_reason, "
                "outcome=EXCLUDED.outcome, fees=EXCLUDED.fees",
                (trade_id, f["pnl_abs"], f["pnl_pct"], f.get("realized_r"), f.get("planned_r"),
                 f.get("mfe_r"), f.get("mae_r"), f.get("exit_efficiency"),
                 f.get("counterfactual_r"), f.get("mgmt_contribution_r"),
                 f["holding_s"], f["exit_reason"], f["outcome"], f.get("fees", 0.0)),
            )

    def get_result(self, trade_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute("SELECT * FROM trade_results WHERE trade_id=%s", (trade_id,)).fetchone()

    def save_review(self, trade_id: int, review: dict) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO trade_reviews(trade_id, review) VALUES (%s,%s) "
                "ON CONFLICT (trade_id) DO UPDATE SET review=EXCLUDED.review, created_at=now()",
                (trade_id, Json(review)),
            )

    def get_review(self, trade_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute("SELECT * FROM trade_reviews WHERE trade_id=%s", (trade_id,)).fetchone()

    # --- 不交易决策（也是要评测的判断）----------------------------------

    def record_decline(
        self, account_id: int, symbol: str, reason: str, *,
        watch_for: str | None = None, recheck_after_hours: float | None = None,
        bias_if_forced: str | None = None, inputs: dict | None = None, transcript=None,
    ) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO declines(account_id, symbol, reason, watch_for, recheck_after_hours, "
                "bias_if_forced, inputs, transcript) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                (account_id, symbol, reason, watch_for, recheck_after_hours, bias_if_forced,
                 Json(inputs) if inputs is not None else None,
                 Json(transcript) if transcript is not None else None),
            ).fetchone()
        return int(row["id"])

    def declines_due_recheck(self, account_id: int, now) -> list[dict]:
        """到期可校验的不交易决策：设了 recheck_after_hours、已过期、还没校验过、且有 bias。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT id, symbol, bias_if_forced, inputs, created_at FROM declines "
                "WHERE account_id=%s AND recheck_after_hours IS NOT NULL "
                "AND bias_if_forced IS NOT NULL AND recheck_outcome IS NULL "
                "AND created_at + (recheck_after_hours * interval '1 hour') <= %s",
                (account_id, now),
            ).fetchall()

    def save_decline_outcome(self, decline_id: int, outcome: dict) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE declines SET recheck_outcome=%s WHERE id=%s", (Json(outcome), decline_id)
            )

    def list_declines(self, account_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT id, account_id, symbol, reason, watch_for, recheck_after_hours, "
                "bias_if_forced, recheck_outcome, created_at "
                "FROM declines WHERE account_id=%s ORDER BY id DESC", (account_id,)
            ).fetchall()

    # --- 状态查询（服务层用）--------------------------------------------

    def closed_without_review(self, account_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT t.* FROM trades t LEFT JOIN trade_reviews r ON r.trade_id=t.id "
                "WHERE t.account_id=%s AND t.status='closed' AND r.trade_id IS NULL ORDER BY t.id",
                (account_id,),
            ).fetchall()

    def reeval_pending(self, trade_id: int) -> bool:
        """是否有未处理的 needs_review（最近一条 needs_review 晚于最近一次 adjust_）。"""
        evs = self.events(trade_id)
        last_need = max((i for i, e in enumerate(evs) if e["kind"] == "needs_review"), default=-1)
        last_adj = max((i for i, e in enumerate(evs) if e["kind"].startswith("adjust_")), default=-1)
        return last_need > last_adj

    # --- 聚合视图 ---------------------------------------------------------

    def timeline(self, trade_id: int) -> dict:
        """单笔交易的全貌：交易行 + 各版计划 + 委托 + 持仓快照 + 事件 + 结果 + 复盘。"""
        return {
            "trade": self.get_trade(trade_id),
            "plans": self.plan_versions(trade_id),
            "orders": self.orders(trade_id),
            "snapshots": self.position_snapshots(trade_id),
            "events": self.events(trade_id),
            "result": self.get_result(trade_id),
            "review": self.get_review(trade_id),
        }

    def scorecard(self, account_id: int) -> dict:
        """账户级评测聚合 v2：胜率/期望R/盈利因子/回撤 + 出场效率/管理贡献/置信度校准/拒绝力。"""
        with self.pool.connection() as conn:
            results = conn.execute(
                "SELECT r.*, p.plan->>'confidence_pct' AS conf "
                "FROM trade_results r JOIN trades t ON t.id=r.trade_id "
                "LEFT JOIN trade_plans p ON p.trade_id=t.id AND p.version=1 "
                "WHERE t.account_id=%s ORDER BY r.closed_at",
                (account_id,),
            ).fetchall()
            acct = conn.execute("SELECT * FROM accounts WHERE id=%s", (account_id,)).fetchone()
            declines = conn.execute(
                "SELECT recheck_outcome FROM declines "
                "WHERE account_id=%s AND recheck_outcome IS NOT NULL", (account_id,)
            ).fetchall()
        n = len(results)
        if n == 0:
            return {"account_id": account_id, "closed_trades": 0,
                    "balance": acct["balance"] if acct else None}
        wins = [r for r in results if r["outcome"] == "win"]
        losses = [r for r in results if r["outcome"] == "loss"]
        gross_win = sum(r["pnl_abs"] for r in wins)
        gross_loss = -sum(r["pnl_abs"] for r in losses)
        rs = [r["realized_r"] for r in results if r["realized_r"] is not None]
        effs = [r["exit_efficiency"] for r in results if r["exit_efficiency"] is not None]
        mgmts = [r["mgmt_contribution_r"] for r in results if r["mgmt_contribution_r"] is not None]
        # 最大回撤：按平仓顺序累计权益曲线
        eq = acct["initial_balance"] if acct else 0.0
        peak, max_dd = eq, 0.0
        for r in results:
            eq += r["pnl_abs"]
            peak = max(peak, eq)
            max_dd = max(max_dd, peak - eq)

        def _avg(xs):
            return round(sum(xs) / len(xs), 3) if xs else None

        return {
            "account_id": account_id,
            "closed_trades": n,
            "win_rate": round(len(wins) / n, 3),
            "avg_r": _avg(rs),
            "expectancy_r": _avg(rs),
            "profit_factor": round(gross_win / gross_loss, 3) if gross_loss > 0 else None,
            "total_pnl": round(sum(r["pnl_abs"] for r in results), 2),
            "max_drawdown": round(max_dd, 2),
            "balance": acct["balance"] if acct else None,
            # v2：出场效率（吃到多少有利波动）+ 管理层相对"不管理"的总贡献
            "avg_exit_efficiency": _avg(effs),
            "total_mgmt_contribution_r": round(sum(mgmts), 3) if mgmts else None,
            "calibration": self._calibration(results),
            "decline_accuracy": self._decline_accuracy(declines),
        }

    @staticmethod
    def _calibration(results: list[dict]) -> list[dict]:
        """置信度校准：按 confidence 分桶对比实际胜率（理想应贴近对角线）。"""
        buckets = [("<45", 0, 45), ("45-55", 45, 55), ("55-65", 55, 65), (">65", 65, 101)]
        out = []
        for label, lo, hi in buckets:
            grp = []
            for r in results:
                try:
                    c = float(r["conf"]) if r["conf"] is not None else None
                except (TypeError, ValueError):
                    c = None
                if c is not None and lo <= c < hi:
                    grp.append(r)
            if grp:
                wr = sum(1 for r in grp if r["outcome"] == "win") / len(grp)
                out.append({"bucket": label, "n": len(grp), "win_rate": round(wr, 3)})
        return out

    @staticmethod
    def _decline_accuracy(declines: list[dict]) -> dict | None:
        """拒绝力：到期已校验的不交易决策里，判对的比例（recheck_outcome.correct）。"""
        verified = [d["recheck_outcome"] for d in declines if d["recheck_outcome"]]
        if not verified:
            return None
        correct = sum(1 for o in verified if o.get("correct"))
        return {"verified": len(verified), "correct": correct,
                "accuracy": round(correct / len(verified), 3)}
