"""PostgreSQL 存储：对话 + 消息。

content_json 存原始 content blocks（含 tool_use / tool_result），原样喂回 Claude。
连接来自共用连接池（db.make_pool）；每次操作借一条连接，事务由 pool.connection() 收尾。
"""

from __future__ import annotations

import json
from typing import Any

from psycopg_pool import ConnectionPool

_SCHEMA = """
CREATE TABLE IF NOT EXISTS conversations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role            TEXT NOT NULL,
    content_json    TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_messages_conv ON messages(conversation_id);
"""


class Storage:
    def __init__(self, pool: ConnectionPool) -> None:
        self.pool = pool
        self.init_db()

    def init_db(self) -> None:
        with self.pool.connection() as conn:
            conn.execute(_SCHEMA)

    # --- 对话 -------------------------------------------------------------

    def create_conversation(self, title: str) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO conversations(title) VALUES (%s) RETURNING id",
                (title,),
            ).fetchone()
            return int(row["id"])

    def conversation_exists(self, conversation_id: int) -> bool:
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT 1 FROM conversations WHERE id = %s", (conversation_id,)
            ).fetchone()
            return row is not None

    def get_conversation(self, conversation_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT id, title, created_at, updated_at FROM conversations WHERE id = %s",
                (conversation_id,),
            ).fetchone()

    def list_conversations(self) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT id, title, created_at, updated_at FROM conversations "
                "ORDER BY updated_at DESC"
            ).fetchall()

    def touch_conversation(self, conversation_id: int) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE conversations SET updated_at = now() WHERE id = %s",
                (conversation_id,),
            )

    # --- 消息 -------------------------------------------------------------

    def add_message(self, conversation_id: int, role: str, content: Any) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO messages(conversation_id, role, content_json) VALUES (%s,%s,%s)",
                (conversation_id, role, json.dumps(content, ensure_ascii=False)),
            )

    def get_history(self, conversation_id: int) -> list[dict]:
        """返回可直接喂给 Claude 的 messages 列表。"""
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT role, content_json FROM messages "
                "WHERE conversation_id = %s ORDER BY id ASC",
                (conversation_id,),
            ).fetchall()
        return [
            {"role": r["role"], "content": json.loads(r["content_json"])} for r in rows
        ]

    def delete_conversation(self, conversation_id: int) -> None:
        # 消息通过 ON DELETE CASCADE 一并删除
        with self.pool.connection() as conn:
            conn.execute("DELETE FROM conversations WHERE id = %s", (conversation_id,))

    def update_title(self, conversation_id: int, title: str) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE conversations SET title = %s, updated_at = now() WHERE id = %s",
                (title, conversation_id),
            )


def display_messages(raw: list[dict]) -> list[dict]:
    """把存储的原始 content blocks 折叠成干净的对话气泡 [{role, content}]。

    user 纯文本保留；user 的 tool_result（list）跳过；assistant 只取 text 块
    （丢 tool_use/thinking）。一次工具往返因此塌缩成「用户问题 + 最终回答」。
    """
    out: list[dict] = []
    for msg in raw:
        role = msg.get("role")
        content = msg.get("content")
        if role == "user":
            if isinstance(content, str):
                out.append({"role": "user", "content": content})
            # list = tool_result，内部数据，跳过
        elif role == "assistant":
            if isinstance(content, str):
                text = content
            else:
                text = "\n".join(
                    b.get("text", "")
                    for b in content
                    if isinstance(b, dict) and b.get("type") == "text" and b.get("text")
                )
            if text:
                out.append({"role": "assistant", "content": text})
    return out
