"""K5 归并层：规范知识节点 + 提及记录 + 生命周期状态（判据与规则见 merge-guide.md）。

节点=耐久知识的规范形态（method/concept 全量、claim 仅重申）；单元=不可变证据。
状态是派生量：recompute 按 merge-guide §3 的规则 v1 重算，人工只能置 retired。

用法：
  python -m analyzer.knowledge.nodes export            # 导出待归并单元清单
  python -m analyzer.knowledge.nodes import <file>     # 导入归并 JSON（整文件事务）
  python -m analyzer.knowledge.nodes recompute         # 重算全部节点状态
  python -m analyzer.knowledge.nodes retire <id> <理由> # 人工退役节点
"""

from __future__ import annotations

import json
import pathlib
import sys

from psycopg_pool import ConnectionPool

from ..config import get_settings
from ..db import make_pool

_SCHEMA = """
CREATE TABLE IF NOT EXISTS knowledge_nodes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       TEXT NOT NULL,               -- claim|method|concept（跨 kind 不归并）
    title      TEXT NOT NULL,               -- 规范名（≤30 字，检索抓手）
    canonical  TEXT NOT NULL,               -- 归一化陈述（supersedes 时更新为最新表述）
    status     TEXT NOT NULL DEFAULT 'active',  -- active|corroborated|verified|contested|retired
    tags       TEXT[] NOT NULL DEFAULT '{}',
    notes      TEXT,                        -- 归并裁量/演进链/退役理由
    merger_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS node_attestations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id    BIGINT NOT NULL REFERENCES knowledge_nodes(id) ON DELETE CASCADE,
    unit_id    BIGINT NOT NULL UNIQUE REFERENCES knowledge_units(id) ON DELETE CASCADE,
    relation   TEXT NOT NULL DEFAULT 'restates',  -- restates|refines|supersedes|contradicts
    note       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_attest_node ON node_attestations(node_id);

-- K6：节点间关系边（无向，a<b 归一；判据见 merge-guide §6）
CREATE TABLE IF NOT EXISTS node_relations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    a_node     BIGINT NOT NULL REFERENCES knowledge_nodes(id) ON DELETE CASCADE,
    b_node     BIGINT NOT NULL REFERENCES knowledge_nodes(id) ON DELETE CASCADE,
    relation   TEXT NOT NULL,                -- conflicts|relates
    note       TEXT NOT NULL,                -- 对立点/关联理由（必填）
    merger_version TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (a_node < b_node),
    UNIQUE (a_node, b_node, relation)
);
"""

_RELATIONS = {"restates", "refines", "supersedes", "contradicts"}
_EDGE_RELATIONS = {"conflicts", "relates"}


class NodeStore:
    def __init__(self, pool: ConnectionPool) -> None:
        self.pool = pool
        with pool.connection() as conn:
            conn.execute(_SCHEMA)

    # --- 导入（整文件事务，校验见 merge-guide §4.3）-------------------------

    def import_nodes(self, doc: dict) -> list[int]:
        version = str(doc["merger_version"])
        nodes = doc["nodes"]
        ids: list[int] = []
        with self.pool.connection() as conn, conn.transaction():
            for i, n in enumerate(nodes):
                units = n.get("units") or []
                if not units:
                    raise ValueError(f"nodes[{i}] 没有提及单元")
                bad = [u for u in units if u.get("relation", "restates") not in _RELATIONS]
                if bad:
                    raise ValueError(f"nodes[{i}] 非法 relation：{bad}")
                unit_ids = [int(u["id"]) for u in units]
                rows = conn.execute(
                    "SELECT id, kind, payload->>'asset_symbol' AS sym FROM knowledge_units "
                    "WHERE id = ANY(%s)", (unit_ids,)).fetchall()
                found = {r["id"]: r for r in rows}
                missing = [u for u in unit_ids if u not in found]
                if missing:
                    raise ValueError(f"nodes[{i}]（{n['title']}）单元不存在：{missing}")
                kinds = {found[u]["kind"] for u in unit_ids}
                if kinds != {n["kind"]}:
                    raise ValueError(f"nodes[{i}]（{n['title']}）kind 不一致：{kinds} vs {n['kind']}")
                if n["kind"] == "claim":
                    syms = {found[u]["sym"] for u in unit_ids}
                    if len(syms) > 1:
                        raise ValueError(f"nodes[{i}]（{n['title']}）claim 重申须同标的：{syms}")
                taken = conn.execute(
                    "SELECT unit_id FROM node_attestations WHERE unit_id = ANY(%s)",
                    (unit_ids,)).fetchall()
                if taken:
                    raise ValueError(f"nodes[{i}]（{n['title']}）单元已归属其他节点：{[t['unit_id'] for t in taken]}")

                row = conn.execute(
                    "INSERT INTO knowledge_nodes(kind, title, canonical, tags, notes, merger_version) "
                    "VALUES (%s,%s,%s,%s,%s,%s) RETURNING id",
                    (n["kind"], n["title"], n["canonical"], n.get("tags") or [],
                     n.get("notes"), version)).fetchone()
                for u in units:
                    conn.execute(
                        "INSERT INTO node_attestations(node_id, unit_id, relation, note) "
                        "VALUES (%s,%s,%s,%s)",
                        (row["id"], int(u["id"]), u.get("relation", "restates"), u.get("note")))
                ids.append(int(row["id"]))
        return ids

    # --- K6：关系边（无向，导入时按 id 归一；判据见 merge-guide §6）----------

    def import_relations(self, doc: dict) -> int:
        version = str(doc["merger_version"])
        n = 0
        with self.pool.connection() as conn, conn.transaction():
            for i, e in enumerate(doc["relations"]):
                rel = e["relation"]
                if rel not in _EDGE_RELATIONS:
                    raise ValueError(f"relations[{i}] 非法 relation：{rel}")
                if not e.get("note"):
                    raise ValueError(f"relations[{i}] note 必填（对立点/关联理由）")
                a, b = sorted((int(e["a"]), int(e["b"])))
                if a == b:
                    raise ValueError(f"relations[{i}] 自环：{a}")
                missing = [x for x in (a, b) if conn.execute(
                    "SELECT 1 FROM knowledge_nodes WHERE id=%s", (x,)).fetchone() is None]
                if missing:
                    raise ValueError(f"relations[{i}] 节点不存在：{missing}")
                conn.execute(
                    "INSERT INTO node_relations(a_node, b_node, relation, note, merger_version) "
                    "VALUES (%s,%s,%s,%s,%s) ON CONFLICT (a_node, b_node, relation) DO NOTHING",
                    (a, b, rel, e["note"], version))
                n += 1
        return n

    def list_relations(self, *, relation: str | None = None) -> list[dict]:
        cond = "WHERE r.relation=%s" if relation else ""
        params: tuple = (relation,) if relation else ()
        with self.pool.connection() as conn:
            return conn.execute(f"""
                SELECT r.id, r.relation, r.note, r.created_at,
                  a.id AS a_id, a.title AS a_title, a.kind AS a_kind, a.status AS a_status,
                  b.id AS b_id, b.title AS b_title, b.kind AS b_kind, b.status AS b_status
                FROM node_relations r
                JOIN knowledge_nodes a ON a.id=r.a_node
                JOIN knowledge_nodes b ON b.id=r.b_node
                {cond} ORDER BY r.relation, r.id""", params).fetchall()

    def relations_for(self, node_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute("""
                SELECT r.relation, r.note,
                  CASE WHEN r.a_node=%s THEN r.b_node ELSE r.a_node END AS other_id,
                  n.title AS other_title, n.kind AS other_kind, n.status AS other_status
                FROM node_relations r
                JOIN knowledge_nodes n ON n.id = CASE WHEN r.a_node=%s THEN r.b_node ELSE r.a_node END
                WHERE r.a_node=%s OR r.b_node=%s ORDER BY r.relation""",
                (node_id, node_id, node_id, node_id)).fetchall()

    # --- 生命周期状态重算（规则 v1，见 merge-guide §3）----------------------

    def recompute(self) -> dict[str, int]:
        changed: dict[str, int] = {}
        with self.pool.connection() as conn:
            rows = conn.execute("""
                SELECT n.id, n.status,
                  bool_or(a.relation='contradicts') AS contradicted,
                  count(DISTINCT u.content_id) AS n_contents,
                  count(*) FILTER (WHERE s.outcome='hit') AS hit,
                  count(*) FILTER (WHERE s.outcome='partial') AS partial,
                  count(*) FILTER (WHERE s.outcome='miss') AS miss
                FROM knowledge_nodes n
                JOIN node_attestations a ON a.node_id=n.id
                JOIN knowledge_units u ON u.id=a.unit_id
                LEFT JOIN claim_scores s ON s.unit_id=u.id
                GROUP BY n.id, n.status""").fetchall()
            for r in rows:
                if r["status"] == "retired":            # 人工置位，重算不覆盖
                    continue
                n_scored = r["hit"] + r["partial"] + r["miss"]
                rate = (r["hit"] + 0.5 * r["partial"]) / n_scored if n_scored else None
                if r["contradicted"] or (n_scored >= 3 and rate is not None and rate <= 0.35):
                    st = "contested"
                elif n_scored >= 3 and rate is not None and rate >= 0.65:
                    st = "verified"
                elif r["n_contents"] >= 2:
                    st = "corroborated"
                else:
                    st = "active"
                if st != r["status"]:
                    conn.execute("UPDATE knowledge_nodes SET status=%s, updated_at=now() WHERE id=%s",
                                 (st, r["id"]))
                    changed[st] = changed.get(st, 0) + 1
        return changed

    def retire(self, node_id: int, reason: str) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "UPDATE knowledge_nodes SET status='retired', updated_at=now(), "
                "notes = COALESCE(notes || E'\\n', '') || %s WHERE id=%s",
                (f"[retired] {reason}", node_id))

    # --- 查询（API 用）------------------------------------------------------

    def list_nodes(self, *, kind: str | None = None, status: str | None = None,
                   tag: str | None = None, cross_source: bool = False,
                   limit: int = 300) -> list[dict]:
        cond, params = [], []
        if kind:
            cond.append("n.kind=%s"); params.append(kind)
        if status:
            cond.append("n.status=%s"); params.append(status)
        if tag:
            cond.append("%s = ANY(n.tags)"); params.append(tag)
        where = ("WHERE " + " AND ".join(cond)) if cond else ""
        having = "HAVING count(DISTINCT u.creator_id) >= 2" if cross_source else ""
        with self.pool.connection() as conn:
            return conn.execute(f"""
                SELECT n.*, count(a.id) AS n_attest,
                  count(DISTINCT u.creator_id) AS n_creators,
                  count(DISTINCT u.content_id) AS n_contents,
                  min(u.published_at) AS first_seen, max(u.published_at) AS last_seen,
                  count(*) FILTER (WHERE s.outcome='hit') AS hit,
                  count(*) FILTER (WHERE s.outcome='partial') AS partial,
                  count(*) FILTER (WHERE s.outcome='miss') AS miss
                FROM knowledge_nodes n
                JOIN node_attestations a ON a.node_id=n.id
                JOIN knowledge_units u ON u.id=a.unit_id
                LEFT JOIN claim_scores s ON s.unit_id=u.id
                {where}
                GROUP BY n.id
                {having}
                ORDER BY n_attest DESC, n.updated_at DESC LIMIT %s""",
                (*params, limit)).fetchall()

    def get_node(self, node_id: int) -> dict | None:
        with self.pool.connection() as conn:
            node = conn.execute("SELECT * FROM knowledge_nodes WHERE id=%s", (node_id,)).fetchone()
            if node is None:
                return None
            node["attestations"] = conn.execute("""
                SELECT a.relation, a.note, u.id AS unit_id, u.kind, u.quote, u.locator,
                  u.published_at, u.tags, u.payload, cr.name AS creator,
                  c.id AS content_id, c.title AS content_title,
                  COALESCE((SELECT json_agg(json_build_object('horizon_label', s.horizon_label,
                    'outcome', s.outcome) ORDER BY s.horizon_label)
                    FROM claim_scores s WHERE s.unit_id=u.id), '[]') AS scores
                FROM node_attestations a
                JOIN knowledge_units u ON u.id=a.unit_id
                JOIN creators cr ON cr.id=u.creator_id
                JOIN contents c ON c.id=u.content_id
                WHERE a.node_id=%s ORDER BY u.published_at, u.id""", (node_id,)).fetchall()
        node["relations"] = self.relations_for(node_id)
        return node

    def seed_singletons(self, *, merger_version: str) -> int:
        """把尚未挂节点的 method/concept 每条建单例节点（title/canonical 机械派生自
        payload，不涉裁量——人工判断只负责'哪些不是单例'）。claim 不建（见 merge-guide §0）。"""
        n = 0
        with self.pool.connection() as conn, conn.transaction():
            rows = conn.execute("""
                SELECT u.id, u.kind, u.tags, u.payload FROM knowledge_units u
                WHERE u.kind IN ('method','concept')
                  AND NOT EXISTS (SELECT 1 FROM node_attestations a WHERE a.unit_id=u.id)
                ORDER BY u.id""").fetchall()
            for r in rows:
                p = r["payload"]
                if r["kind"] == "method":
                    title, canonical = p["name"][:60], p.get("summary") or p["name"]
                else:
                    canonical = p["canonical_statement"]
                    title = canonical.split("：")[0].split("——")[0][:30]
                node = conn.execute(
                    "INSERT INTO knowledge_nodes(kind, title, canonical, tags, notes, merger_version) "
                    "VALUES (%s,%s,%s,%s,%s,%s) RETURNING id",
                    (r["kind"], title, canonical, r["tags"], "[auto] 单例种子（标题机械派生）",
                     merger_version)).fetchone()
                conn.execute(
                    "INSERT INTO node_attestations(node_id, unit_id, relation) VALUES (%s,%s,'restates')",
                    (node["id"], r["id"]))
                n += 1
        return n

    def export_pending(self) -> list[dict]:
        """待归并清单：尚未挂节点的全部单元（紧凑行，归并会话的输入）。"""
        with self.pool.connection() as conn:
            return conn.execute("""
                SELECT u.id, u.kind, u.content_id, cr.name AS creator, u.published_at::date AS pub,
                  u.tags, u.payload
                FROM knowledge_units u JOIN creators cr ON cr.id=u.creator_id
                WHERE NOT EXISTS (SELECT 1 FROM node_attestations a WHERE a.unit_id=u.id)
                ORDER BY u.kind, u.id""").fetchall()


def _headline(kind: str, p: dict) -> str:
    if kind == "claim":
        bits = [p.get("asset_symbol") or p.get("asset_text") or "?", p.get("direction") or ""]
        m = p.get("magnitude") or {}
        for k in ("target", "low", "high", "pct"):
            if m.get(k) is not None:
                bits.append(f"{k}={m[k]}")
        bits.append(p.get("verifiability", ""))
        return " ".join(str(b) for b in bits if b)
    if kind == "method":
        return p.get("name", "?")
    return p.get("canonical_statement", "?")


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "export"
    pool = make_pool(get_settings().pg_knowledge_conninfo)
    try:
        ns = NodeStore(pool)
        if cmd == "export":
            for r in ns.export_pending():
                print(f"#{r['id']:<4} {r['kind']:<8} {r['creator'][:6]:<6} c{r['content_id']:<3} "
                      f"{r['pub']}  {_headline(r['kind'], r['payload'])[:80]}")
        elif cmd == "import":
            doc = json.loads(pathlib.Path(sys.argv[2]).read_text())
            ids = ns.import_nodes(doc)
            print(f"入库 {len(ids)} 个节点（id {ids[0]}..{ids[-1]}）")
            print("状态重算：", ns.recompute() or "无变化")
        elif cmd == "import-relations":
            doc = json.loads(pathlib.Path(sys.argv[2]).read_text())
            print(f"关系边入库 {ns.import_relations(doc)} 条")
        elif cmd == "seed-singletons":
            n = ns.seed_singletons(merger_version=sys.argv[2] if len(sys.argv) > 2 else "merge-v1")
            print(f"单例种子 {n} 个")
            print("状态重算：", ns.recompute() or "无变化")
        elif cmd == "recompute":
            print("状态重算：", ns.recompute() or "无变化")
        elif cmd == "retire":
            ns.retire(int(sys.argv[2]), sys.argv[3])
            print("已退役", sys.argv[2])
        else:
            raise SystemExit(f"未知命令：{cmd}")
    finally:
        pool.close()


if __name__ == "__main__":
    main()
