"""标的参考数据：公司资料 + 按标的的新闻时间线（与 daily_bars 同库同层）。

**为什么放在 `fanisl_knowledge`**：它和 `daily_bars` 是同一类东西——按 `assets.py` 的
规范 id 主键、给标的工作台读的参考数据。放这里，标的档案一次查询就能带出，不必跨库。
行情时序库那边的 `catalyst_items` 是另一回事：那是"最新快照"语义（先删后插），
给对话工具看当下有什么新闻用；这里的 `news_items` 是**追加式、可回溯**的时间线。

用法（幂等，可重复跑）：
    python -m analyzer.knowledge.reference --profiles          # 刷公司资料
    python -m analyzer.knowledge.reference --news --days 14    # 追加最近 14 天的新闻
    python -m analyzer.knowledge.reference --earnings          # 刷财报日历（只问个股）
    python -m analyzer.knowledge.reference --triage            # 动态降噪（规则 + LLM）
    python -m analyzer.knowledge.reference --triage --rules-only
    python -m analyzer.knowledge.reference --profiles --news --earnings --asset NVDA

**限速**：Polygon 免费档 5 次/分，所以刷资料时每个标的之间 sleep（`--pace` 可调）。
Finnhub 60 次/分，新闻那一轮不用等。
"""

from __future__ import annotations

import datetime as dt
import sys
import time

from psycopg.types.json import Json
from psycopg_pool import ConnectionPool

from .. import assets
from ..config import get_settings
from ..data.asset_news_source import fetch_company_news
from ..data.company_source import build_profile
from ..data.earnings_source import fetch_earnings
from ..db import make_pool

# 有 ticker 的类别才去问公司资料与公司新闻；其余（指数/金属/商品/利率/汇率/加密）两个源都不收录。
TICKER_CLASSES = ("stock", "etf")
# 只有个股报财报。ETF 实测返回 0 条（SOXX），别把空结果当成"抓失败"。
EARNINGS_CLASSES = ("stock",)

_SCHEMA = """
CREATE TABLE IF NOT EXISTS asset_profiles (
    asset        TEXT PRIMARY KEY,
    name         TEXT,
    description  TEXT,
    industry     TEXT,
    exchange     TEXT,
    country      TEXT,
    currency     TEXT,
    cik          TEXT,
    homepage     TEXT,
    logo         TEXT,
    listed_on    DATE,
    employees    INT,
    market_cap   DOUBLE PRECISION,
    shares_out   DOUBLE PRECISION,
    metrics      JSONB,
    sources      JSONB,          -- 逐字段的来源，口径存疑时能查是谁给的
    fetched_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 追加式：同一条新闻重复抓到就跳过，**从不删旧条**——标的页要的是可回溯的时间线。
CREATE TABLE IF NOT EXISTS news_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset        TEXT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL,
    title        TEXT NOT NULL,
    summary      TEXT,
    url          TEXT,
    source       TEXT,
    provider     TEXT NOT NULL,
    image_url    TEXT,
    dedup_key    TEXT NOT NULL,
    fetched_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (asset, dedup_key)
);
CREATE INDEX IF NOT EXISTS idx_news_asset_time ON news_items(asset, published_at DESC);
-- 降噪结果。**原始记录一条不删**：规则会改，改了要能对存量重判，删了就永远回不去。
ALTER TABLE news_items ADD COLUMN IF NOT EXISTS relevance TEXT;      -- core|context|noise|NULL=未判
ALTER TABLE news_items ADD COLUMN IF NOT EXISTS note TEXT;           -- 一句中文：发生了什么变化
ALTER TABLE news_items ADD COLUMN IF NOT EXISTS classifier TEXT;     -- rules|gemini:<model>
ALTER TABLE news_items ADD COLUMN IF NOT EXISTS classified_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_news_unclassified ON news_items(asset) WHERE relevance IS NULL;

-- 财报等日历型事件。**这张是 upsert 不是追加**：日期会挪、预期会被修正，要的是最新一版；
-- news_items 是追加式，因为那边要的是"当时报道了什么"的可回溯记录。两种语义都要，别混。
CREATE TABLE IF NOT EXISTS asset_events (
    asset      TEXT NOT NULL,
    kind       TEXT NOT NULL,              -- earnings
    event_date DATE NOT NULL,
    session    TEXT,                       -- bmo 盘前 | amc 盘后 | dmh 盘中
    payload    JSONB,                      -- quarter/fiscal_year/eps_*/revenue_*
    source     TEXT NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (asset, kind, event_date)
);
CREATE INDEX IF NOT EXISTS idx_events_asset_date ON asset_events(asset, event_date);
"""


def dedup_key(item: dict) -> str:
    """优先按 url，其次按标题归一化——同一条新闻在不同抓取轮次里 id 会变，url 不会。"""
    url = (item.get("url") or "").strip().rstrip("/").lower()
    if url:
        return url
    return "".join((item.get("title") or "").lower().split())


class ReferenceStore:
    def __init__(self, pool: ConnectionPool) -> None:
        self.pool = pool
        with pool.connection() as conn:
            conn.execute(_SCHEMA)

    # --- 公司资料 --------------------------------------------------------

    def upsert_profile(self, asset: str, profile: dict) -> None:
        columns = ("name", "description", "industry", "exchange", "country", "currency", "cik",
                   "homepage", "logo", "listed_on", "employees", "market_cap", "shares_out")
        values = [profile.get(column) for column in columns]
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO asset_profiles(asset, name, description, industry, exchange, country, "
                "currency, cik, homepage, logo, listed_on, employees, market_cap, shares_out, "
                "metrics, sources, fetched_at) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s, now()) "
                "ON CONFLICT (asset) DO UPDATE SET "
                "name=EXCLUDED.name, description=EXCLUDED.description, industry=EXCLUDED.industry, "
                "exchange=EXCLUDED.exchange, country=EXCLUDED.country, currency=EXCLUDED.currency, "
                "cik=EXCLUDED.cik, homepage=EXCLUDED.homepage, logo=EXCLUDED.logo, "
                "listed_on=EXCLUDED.listed_on, employees=EXCLUDED.employees, "
                "market_cap=EXCLUDED.market_cap, shares_out=EXCLUDED.shares_out, "
                "metrics=EXCLUDED.metrics, sources=EXCLUDED.sources, fetched_at=now()",
                (asset, *values, Json(profile.get("metrics")), Json(profile.get("sources"))),
            )

    def profile(self, asset: str) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute("SELECT * FROM asset_profiles WHERE asset=%s", (asset,)).fetchone()

    def profile_coverage(self) -> dict[str, dt.datetime]:
        with self.pool.connection() as conn:
            rows = conn.execute("SELECT asset, fetched_at FROM asset_profiles").fetchall()
        return {row["asset"]: row["fetched_at"] for row in rows}

    # --- 新闻 ------------------------------------------------------------

    def add_news(self, asset: str, items: list[dict]) -> int:
        """追加入库，按 (asset, dedup_key) 去重。返回**新增**条数。"""
        if not items:
            return 0
        added = 0
        with self.pool.connection() as conn:
            for item in items:
                key = dedup_key(item)
                if not key:
                    continue
                row = conn.execute(
                    "INSERT INTO news_items(asset, published_at, title, summary, url, source, "
                    "provider, image_url, dedup_key) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s) "
                    "ON CONFLICT (asset, dedup_key) DO NOTHING RETURNING id",
                    (asset, item["published_at"], item["title"], item.get("summary"),
                     item.get("url"), item.get("source"), item.get("provider", "unknown"),
                     item.get("image_url"), key),
                ).fetchone()
                if row is not None:
                    added += 1
        return added

    def news(self, asset: str, *, limit: int = 40,
             include: tuple[str, ...] = ("core", "context")) -> list[dict]:
        """某标的的动态。默认只给判过且**不是噪音**的；`include=()` 表示不过滤（全给）。

        未判的（relevance IS NULL）也给——降噪是异步跑的，没跑到之前不能让页面变空。
        """
        clause = ""
        params: list = [asset]
        if include:
            clause = " AND (relevance IS NULL OR relevance = ANY(%s))"
            params.append(list(include))
        params.append(limit)
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT id, published_at, title, summary, url, source, provider, image_url, "
                f"relevance, note FROM news_items WHERE asset=%s{clause} "
                "ORDER BY published_at DESC, id DESC LIMIT %s", tuple(params),
            ).fetchall()

    def news_counts(self, asset: str) -> dict[str, int]:
        """按 relevance 分组的条数——页面要能说"另有 N 条被判为噪音"。"""
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT COALESCE(relevance, 'unclassified') AS k, count(*) AS n "
                "FROM news_items WHERE asset=%s GROUP BY 1", (asset,)).fetchall()
        return {row["k"]: row["n"] for row in rows}

    # --- 日历事件（财报）------------------------------------------------

    def upsert_events(self, asset: str, kind: str, items: list[dict], *, source: str) -> int:
        if not items:
            return 0
        with self.pool.connection() as conn:
            for item in items:
                conn.execute(
                    "INSERT INTO asset_events(asset, kind, event_date, session, payload, source, "
                    "fetched_at) VALUES (%s,%s,%s,%s,%s,%s, now()) "
                    "ON CONFLICT (asset, kind, event_date) DO UPDATE SET "
                    "session=EXCLUDED.session, payload=EXCLUDED.payload, "
                    "source=EXCLUDED.source, fetched_at=now()",
                    (asset, kind, item["event_date"], item.get("session"),
                     Json(item.get("payload")), source),
                )
        return len(items)

    def events(self, asset: str, *, kind: str | None = None) -> list[dict]:
        """按日期升序。前端自己按今天切"已公布/下一次"。"""
        with self.pool.connection() as conn:
            if kind:
                return conn.execute(
                    "SELECT asset, kind, event_date, session, payload, source FROM asset_events "
                    "WHERE asset=%s AND kind=%s ORDER BY event_date", (asset, kind)).fetchall()
            return conn.execute(
                "SELECT asset, kind, event_date, session, payload, source FROM asset_events "
                "WHERE asset=%s ORDER BY event_date", (asset,)).fetchall()

    def next_events(self) -> dict[str, dict]:
        """每个标的**下一次**未到的事件——给列表页与覆盖标记用，一次查完不做 N+1。"""
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT DISTINCT ON (asset) asset, kind, event_date, session, payload "
                "FROM asset_events WHERE event_date >= current_date "
                "ORDER BY asset, event_date").fetchall()
        return {row["asset"]: row for row in rows}

    def news_coverage(self) -> dict[str, dict]:
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT asset, count(*) AS n, max(published_at) AS latest "
                "FROM news_items GROUP BY asset").fetchall()
        return {row["asset"]: row for row in rows}

    def news_coverage_for(self, asset: str) -> dict | None:
        """单个标的的新闻覆盖。档案页只要自己那一行——全表聚合是列表页才需要的。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT asset, count(*) AS n, max(published_at) AS latest, "
                "count(*) FILTER (WHERE relevance='noise') AS noise "
                "FROM news_items WHERE asset=%s GROUP BY asset", (asset,)).fetchone()


def earnings_assets() -> list[assets.Asset]:
    return [a for a in ticker_assets() if a.asset_class in EARNINGS_CLASSES]


def ticker_assets() -> list[assets.Asset]:
    """会去问外部源的标的：有 ticker 的类别，且 yfinance ticker 与 id 同名（= 真 ticker）。"""
    out = []
    for asset in assets.all_assets():
        if asset.asset_class not in TICKER_CLASSES:
            continue
        if asset.yf and asset.yf != asset.id:
            continue   # 代理映射（如 WTI→CL=F）不是真 ticker，问了也没有公司
        out.append(asset)
    return out


def refresh_profiles(pool, *, only: str | None = None, pace_s: float = 12.0) -> dict:
    """刷公司资料。Polygon 免费档 5 次/分，逐个之间 sleep(pace_s)。"""
    settings = get_settings()
    store = ReferenceStore(pool)
    targets = [a for a in ticker_assets() if only is None or a.id == only]
    ok, missing = 0, []
    for index, asset in enumerate(targets):
        profile = build_profile(asset.id, polygon_key=settings.polygon_api_key,
                                finnhub_key=settings.finnhub_api_key)
        if profile is None:
            missing.append(asset.id)
        else:
            store.upsert_profile(asset.id, profile)
            ok += 1
        print(f"  {asset.id:6s} {'ok' if profile else '无资料'}", flush=True)
        if pace_s > 0 and index < len(targets) - 1:
            time.sleep(pace_s)
    return {"ok": ok, "missing": missing, "total": len(targets)}


def refresh_news(pool, *, only: str | None = None, days: int = 14) -> dict:
    """追加最近 days 天的按标的新闻（Finnhub 60 次/分，不用限速）。"""
    settings = get_settings()
    store = ReferenceStore(pool)
    targets = [a for a in ticker_assets() if only is None or a.id == only]
    added, empty = 0, []
    for asset in targets:
        items = fetch_company_news(asset.id, settings.finnhub_api_key, days=days)
        if not items:
            empty.append(asset.id)
            continue
        n = store.add_news(asset.id, items)
        added += n
        print(f"  {asset.id:6s} 抓到 {len(items)}，新增 {n}", flush=True)
    return {"added": added, "empty": empty, "total": len(targets)}


def refresh_earnings(pool, *, only: str | None = None) -> dict:
    """刷财报日历（Finnhub 60 次/分，不用限速）。只问个股。"""
    settings = get_settings()
    store = ReferenceStore(pool)
    targets = [a for a in earnings_assets() if only is None or a.id == only]
    written, empty = 0, []
    for asset in targets:
        rows = fetch_earnings(asset.id, settings.finnhub_api_key)
        if not rows:
            empty.append(asset.id)
            continue
        written += store.upsert_events(asset.id, "earnings", rows, source="finnhub")
        print(f"  {asset.id:6s} {len(rows)} 个时点", flush=True)
    return {"written": written, "empty": empty, "total": len(targets)}


def main() -> None:
    args = sys.argv[1:]
    only = args[args.index("--asset") + 1].upper() if "--asset" in args else None
    days = int(args[args.index("--days") + 1]) if "--days" in args else 14
    pace = float(args[args.index("--pace") + 1]) if "--pace" in args else 12.0
    pool = make_pool(get_settings().pg_knowledge_conninfo)
    try:
        # **先快后慢**：新闻与财报各只要几十次 Finnhub 调用（60 次/分），一两分钟就落库；
        # 公司资料受 Polygon 5 次/分限速要跑十几分钟。三块一起要时把慢的放最后，
        # 页面能早点有内容，中途断线也只损失最贵的那一块。
        if "--news" in args:
            print("新闻：")
            print(" ", refresh_news(pool, only=only, days=days))
        if "--earnings" in args:
            print("财报日历：")
            print(" ", refresh_earnings(pool, only=only))
        if "--triage" in args:
            from . import news_triage

            print("动态降噪：")
            print(" ", news_triage.run(pool, get_settings(), only=only,
                                       use_llm="--rules-only" not in args))
        if "--profiles" in args:
            print("公司资料：")
            print(" ", refresh_profiles(pool, only=only, pace_s=pace))
        if not ({"--profiles", "--news", "--earnings", "--triage"} & set(args)):
            print(__doc__)
    finally:
        pool.close()


if __name__ == "__main__":
    main()
