"""知识引擎持久化（独立库 fanisl_knowledge）。

L0 contents 追加式不可变（原文永存，下游全部可重放）；L1 units 带 extractor_version
双版本戳；(content_id, extractor_version) 在 extraction_runs 上唯一 = 重跑出新行不覆盖。
"""

from __future__ import annotations

import hashlib

from psycopg.types.json import Json
from psycopg_pool import ConnectionPool

from .models import KnowledgeUnit

_SCHEMA = """
CREATE TABLE IF NOT EXISTS creators (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    lang       TEXT NOT NULL DEFAULT 'zh',
    focus      TEXT,                 -- 擅长资产/主题（自由文本）
    notes      TEXT,
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS creator_handles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT NOT NULL REFERENCES creators(id) ON DELETE CASCADE,
    platform   TEXT NOT NULL,        -- youtube|rss|x|telegram|manual…
    handle     TEXT NOT NULL,        -- @handle / channel_id / feed url
    url        TEXT,
    added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (platform, handle)
);

CREATE TABLE IF NOT EXISTS contents (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id   BIGINT NOT NULL REFERENCES creators(id) ON DELETE CASCADE,
    platform     TEXT NOT NULL,
    url          TEXT,
    content_type TEXT NOT NULL,      -- video|article|post|podcast|manual
    title        TEXT,
    published_at TIMESTAMPTZ,        -- 平台声称的发布时刻（PIT 锚点）
    fetched_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    lang         TEXT,
    raw          TEXT NOT NULL,      -- 全文/转录，永存不改
    dedup_hash   TEXT NOT NULL UNIQUE,
    triage       JSONB,              -- L0 门卫结果
    status       TEXT NOT NULL DEFAULT 'new',  -- new|triaged|awaiting_manual|extracted|skipped
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_contents_status ON contents(status, published_at);

CREATE TABLE IF NOT EXISTS extraction_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id        BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    extractor_version TEXT NOT NULL,
    model             TEXT,
    n_units           INT NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (content_id, extractor_version)
);

CREATE TABLE IF NOT EXISTS knowledge_units (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            BIGINT NOT NULL REFERENCES extraction_runs(id) ON DELETE CASCADE,
    content_id        BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    creator_id        BIGINT NOT NULL,
    published_at      TIMESTAMPTZ,          -- 冗余自 content（PIT 锚点）
    kind              TEXT NOT NULL,        -- claim|method|concept
    quote             TEXT NOT NULL,
    locator           TEXT,
    extractor_version TEXT NOT NULL,
    model             TEXT,
    payload           JSONB NOT NULL,
    tags              TEXT[] NOT NULL DEFAULT '{}',
    ref_price_at_publish DOUBLE PRECISION,  -- claim：发布时刻市价（pit.asof 补）
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_units_kind ON knowledge_units(kind, creator_id, published_at);

CREATE TABLE IF NOT EXISTS claim_scores (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id        BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    eval_ts        TIMESTAMPTZ NOT NULL,
    horizon_label  TEXT NOT NULL,           -- 阶梯标签（如 '2026-08-31' / '30d'）
    outcome        TEXT NOT NULL,           -- hit|miss|partial|condition_not_met|condition_unverifiable|unpriceable|pending
    realized       JSONB,                   -- 实际收益/触及价等
    scorer_version TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (unit_id, horizon_label, scorer_version)
);

CREATE TABLE IF NOT EXISTS spot_checks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id    BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    verdict    TEXT NOT NULL,               -- faithful|unfaithful|unclear
    note       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 视觉笔记的像素凭据：笔记记"画面上写了 63/61/63"，帧让这句话可核。视频被删后
-- 也只剩这两样。文件本体在 data_export/keyframes/（gitignore，可按本表重抓）。
CREATE TABLE IF NOT EXISTS keyframes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    ts_s       INT NOT NULL,               -- 视频内秒偏移（取自视觉笔记时间戳）
    kind       TEXT,                       -- chart|table|text_slide|other
    note       TEXT,                       -- 该时刻的视觉笔记原文（核对对象）
    path       TEXT NOT NULL,              -- 相对 data_export/ 的路径
    height     INT NOT NULL,
    bytes      INT,
    source     TEXT NOT NULL,              -- 提帧通道 ytdlp:<client>（墙再动时可回看）
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (content_id, ts_s)
);
"""


def dedup_hash(raw: str) -> str:
    return hashlib.sha256(raw.strip().encode()).hexdigest()[:32]


class KnowledgeStore:
    def __init__(self, pool: ConnectionPool) -> None:
        self.pool = pool
        with pool.connection() as conn:
            conn.execute(_SCHEMA)

    # --- 信源 -------------------------------------------------------------

    def ensure_creator(self, name: str, *, lang: str = "zh", focus: str | None = None,
                       notes: str | None = None) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO creators(name, lang, focus, notes) VALUES (%s,%s,%s,%s) "
                "ON CONFLICT (name) DO UPDATE SET lang=EXCLUDED.lang RETURNING id",
                (name, lang, focus, notes),
            ).fetchone()
        return int(row["id"])

    def ensure_handle(self, creator_id: int, platform: str, handle: str,
                      url: str | None = None) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO creator_handles(creator_id, platform, handle, url) "
                "VALUES (%s,%s,%s,%s) ON CONFLICT (platform, handle) DO UPDATE "
                "SET url=EXCLUDED.url RETURNING id",
                (creator_id, platform, handle, url),
            ).fetchone()
        return int(row["id"])

    def creators(self) -> list[dict]:
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT c.*, COALESCE(json_agg(json_build_object('platform', h.platform, "
                "'handle', h.handle, 'url', h.url)) FILTER (WHERE h.id IS NOT NULL), '[]') AS handles "
                "FROM creators c LEFT JOIN creator_handles h ON h.creator_id=c.id "
                "GROUP BY c.id ORDER BY c.id",
            ).fetchall()
        return rows

    # --- L0 内容（追加式）--------------------------------------------------

    def upsert_content(self, creator_id: int, *, platform: str, url: str | None,
                       content_type: str, title: str | None, published_at,
                       raw: str, lang: str | None = None,
                       triage: dict | None = None) -> tuple[int, bool]:
        """按 dedup_hash 幂等插入。返回 (content_id, 是否新建)。已存在时不改原文。

        triage 记转录出处（model/channel）。2026-08 的教训：lite 档模型会改写数字，
        事后想圈出受影响的内容却发现库里没留通道记录，只能靠会话日志回溯。
        """
        h = dedup_hash(raw)
        with self.pool.connection() as conn:
            row = conn.execute("SELECT id FROM contents WHERE dedup_hash=%s", (h,)).fetchone()
            if row:
                return int(row["id"]), False
            row = conn.execute(
                "INSERT INTO contents(creator_id, platform, url, content_type, title, "
                "published_at, lang, raw, dedup_hash, triage) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                (creator_id, platform, url, content_type, title, published_at, lang, raw, h,
                 Json(triage) if triage else None),
            ).fetchone()
        return int(row["id"]), True

    def content_url_exists(self, url: str) -> bool:
        """按 URL 判存（批量回填跳过已转录的视频，省 Gemini 开销；raw 哈希去重之外的前置闸）。"""
        with self.pool.connection() as conn:
            return conn.execute("SELECT 1 FROM contents WHERE url=%s LIMIT 1", (url,)).fetchone() is not None

    def set_triage(self, content_id: int, triage: dict, status: str) -> None:
        with self.pool.connection() as conn:
            conn.execute("UPDATE contents SET triage=%s, status=%s WHERE id=%s",
                         (Json(triage), status, content_id))

    def set_status(self, content_id: int, status: str) -> None:
        with self.pool.connection() as conn:
            conn.execute("UPDATE contents SET status=%s WHERE id=%s", (status, content_id))

    def contents_by_status(self, status: str, *, limit: int = 50) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM contents WHERE status=%s ORDER BY published_at NULLS LAST "
                "LIMIT %s", (status, limit),
            ).fetchall()

    def get_content(self, content_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT c.*, cr.name AS creator FROM contents c "
                "JOIN creators cr ON cr.id=c.creator_id WHERE c.id=%s", (content_id,),
            ).fetchone()

    def list_contents(self, *, status: str | None = None, limit: int = 200) -> list[dict]:
        """内容列表（不含 raw 全文，带信源名/字数/单元构成/评分摘要）——前端列表页用。

        默认排除 superseded：重转录后的旧稿是 L0 的历史记录（append-only 不删），但任何
        "这个信源有几期"的计数都不该把同一期算两遍。要看旧稿传 status='superseded'。
        """
        cond = "WHERE c.status=%s" if status else "WHERE c.status <> 'superseded'"
        params: tuple = (status, limit) if status else (limit,)
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT c.id, c.creator_id, cr.name AS creator, c.platform, c.url, "
                f"c.content_type, c.title, c.published_at, c.fetched_at, c.lang, c.status, "
                f"length(c.raw) AS raw_len, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id) AS n_units, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id AND u.kind='claim') AS n_claims, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id AND u.kind='method') AS n_methods, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id AND u.kind='concept') AS n_concepts, "
                f"(SELECT count(*) FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                f" WHERE u.content_id=c.id AND s.outcome='hit') AS n_hit, "
                f"(SELECT count(*) FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                f" WHERE u.content_id=c.id AND s.outcome='partial') AS n_partial, "
                f"(SELECT count(*) FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                f" WHERE u.content_id=c.id AND s.outcome='miss') AS n_miss "
                f"FROM contents c JOIN creators cr ON cr.id=c.creator_id {cond} "
                f"ORDER BY c.published_at DESC NULLS LAST, c.id DESC LIMIT %s", params,
            ).fetchall()

    # --- 关键帧（视觉笔记的像素凭据）-----------------------------------------

    def record_keyframe(self, content_id: int, *, ts_s: int, path: str, height: int,
                        bytes_: int, source: str, kind: str | None = None,
                        note: str | None = None) -> None:
        """(content, ts) 唯一；重抓（如提高清晰度）覆盖同一行。"""
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO keyframes(content_id, ts_s, kind, note, path, height, bytes, source) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s) "
                "ON CONFLICT (content_id, ts_s) DO UPDATE SET "
                "path=EXCLUDED.path, height=EXCLUDED.height, bytes=EXCLUDED.bytes, "
                "source=EXCLUDED.source, kind=COALESCE(EXCLUDED.kind, keyframes.kind), "
                "note=COALESCE(EXCLUDED.note, keyframes.note)",
                (content_id, ts_s, kind, note, path, height, bytes_, source))

    def keyframes_for_content(self, content_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM keyframes WHERE content_id=%s ORDER BY ts_s", (content_id,),
            ).fetchall()

    def keyframe_seconds(self, content_id: int) -> set[int]:
        """已有帧的时间戳集合（回填幂等用）。"""
        with self.pool.connection() as conn:
            rows = conn.execute("SELECT ts_s FROM keyframes WHERE content_id=%s",
                                (content_id,)).fetchall()
        return {int(r["ts_s"]) for r in rows}

    def keyframe(self, keyframe_id: int) -> dict | None:
        """按 id 取单帧（读图端点用 id 而不是路径——路径来自库里，不给穿越的口子）。"""
        with self.pool.connection() as conn:
            return conn.execute("SELECT * FROM keyframes WHERE id=%s", (keyframe_id,)).fetchone()

    def keyframes_near(self, content_id: int, ts_s: int, *, window_s: int) -> list[dict]:
        """某内容里落在 [ts-window, ts+window] 的帧，按与 ts 的距离排序。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT *, abs(ts_s - %s) AS distance_s FROM keyframes "
                "WHERE content_id=%s AND ts_s BETWEEN %s AND %s ORDER BY distance_s, ts_s",
                (ts_s, content_id, ts_s - window_s, ts_s + window_s)).fetchall()

    def keyframe_span(self, content_id: int) -> tuple[int, int] | None:
        """该内容已有帧的时间跨度（判断 locator 是否越界用）。"""
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT min(ts_s) AS lo, max(ts_s) AS hi FROM keyframes WHERE content_id=%s",
                (content_id,)).fetchone()
        return (int(row["lo"]), int(row["hi"])) if row and row["lo"] is not None else None

    # --- L1 提取（版本化重放）----------------------------------------------

    def record_extraction(self, content_id: int, *, extractor_version: str,
                          model: str | None, units: list[KnowledgeUnit],
                          ref_prices: dict[int, float] | None = None) -> list[int]:
        """一次提取运行：runs 上 (content_id, version) 唯一；重复运行报错（换版本号重跑）。
        ref_prices: 单元下标 → 发布时刻市价（claim 用）。返回 unit id 列表。"""
        c = self.get_content(content_id)
        if c is None:
            raise ValueError(f"content {content_id} 不存在")
        ids: list[int] = []
        with self.pool.connection() as conn:
            run = conn.execute(
                "INSERT INTO extraction_runs(content_id, extractor_version, model, n_units) "
                "VALUES (%s,%s,%s,%s) RETURNING id",
                (content_id, extractor_version, model, len(units)),
            ).fetchone()
            for i, u in enumerate(units):
                row = conn.execute(
                    "INSERT INTO knowledge_units(run_id, content_id, creator_id, published_at, "
                    "kind, quote, locator, extractor_version, model, payload, tags, "
                    "ref_price_at_publish) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) "
                    "RETURNING id",
                    (run["id"], content_id, c["creator_id"], c["published_at"], u.kind,
                     u.quote, u.locator, extractor_version, model, Json(u.payload), u.tags,
                     (ref_prices or {}).get(i)),
                ).fetchone()
                ids.append(int(row["id"]))
            conn.execute("UPDATE contents SET status='extracted' WHERE id=%s", (content_id,))
        return ids

    # --- L2 评分（到期机械评分的落库与视图）--------------------------------

    def score_exists(self, unit_id: int, horizon_label: str, scorer_version: str) -> bool:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT 1 FROM claim_scores WHERE unit_id=%s AND horizon_label=%s "
                "AND scorer_version=%s", (unit_id, horizon_label, scorer_version),
            ).fetchone() is not None

    def record_score(self, unit_id: int, *, eval_ts, horizon_label: str, outcome: str,
                     realized: dict, scorer_version: str) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO claim_scores(unit_id, eval_ts, horizon_label, outcome, realized, "
                "scorer_version) VALUES (%s,%s,%s,%s,%s,%s) "
                "ON CONFLICT (unit_id, horizon_label, scorer_version) DO NOTHING",
                (unit_id, eval_ts, horizon_label, outcome, Json(realized), scorer_version))

    def scores_for_content(self, content_id: int) -> list[dict]:
        """某内容全部单元的评分行（前端详情页徽标用）。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT s.* FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                "WHERE u.content_id=%s ORDER BY s.unit_id, s.horizon_label", (content_id,),
            ).fetchall()

    def scoreboard(self) -> list[dict]:
        """信源联赛表：claim 战绩 + 含糊率（按已到期评分行统计；hit=1/partial=0.5 计入命中率）。"""
        with self.pool.connection() as conn:
            return conn.execute("""
                WITH c AS (
                    SELECT u.creator_id, u.id,
                           u.payload->>'verifiability' AS grade
                    FROM knowledge_units u WHERE u.kind='claim'
                ), s AS (
                    SELECT u.creator_id, s.outcome
                    FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id
                )
                SELECT cr.id AS creator_id, cr.name,
                    (SELECT count(*) FROM c WHERE c.creator_id=cr.id)                          AS claims,
                    (SELECT count(*) FROM c WHERE c.creator_id=cr.id AND grade='D')            AS d_claims,
                    (SELECT count(*) FROM knowledge_units u
                      WHERE u.creator_id=cr.id AND u.kind='method')                            AS methods,
                    (SELECT count(*) FROM knowledge_units u
                      WHERE u.creator_id=cr.id AND u.kind='concept')                           AS concepts,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id
                      AND outcome IN ('hit','miss','partial'))                                 AS scored,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id AND outcome='hit')        AS hits,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id AND outcome='partial')    AS partials,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id AND outcome='miss')       AS misses,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id
                      AND outcome='condition_not_met')                                         AS cond_not_met
                FROM creators cr ORDER BY cr.id""").fetchall()

    def units_for_content(self, content_id: int) -> list[dict]:
        """某内容的全部单元（含历史版本；前端详情页用，claim 优先靠前，附评分行）。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT u.*, COALESCE((SELECT json_agg(json_build_object("
                "'horizon_label', s.horizon_label, 'outcome', s.outcome, 'realized', s.realized) "
                "ORDER BY s.horizon_label) FROM claim_scores s WHERE s.unit_id=u.id), '[]') AS scores "
                "FROM knowledge_units u WHERE u.content_id=%s "
                "ORDER BY (u.kind!='claim'), u.id", (content_id,),
            ).fetchall()

    def tags(self) -> list[dict]:
        """标签枢纽：受控词表的实际使用计数（按 kind 细分）。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT tag, count(*) AS n, "
                "count(*) FILTER (WHERE kind='claim') AS n_claims, "
                "count(*) FILTER (WHERE kind='method') AS n_methods, "
                "count(*) FILTER (WHERE kind='concept') AS n_concepts "
                "FROM knowledge_units, unnest(tags) AS tag "
                "GROUP BY tag ORDER BY n DESC, tag").fetchall()

    _UNIT_SCORES_AGG = (
        "COALESCE((SELECT json_agg(json_build_object("
        "'horizon_label', s.horizon_label, 'outcome', s.outcome, 'realized', s.realized) "
        "ORDER BY s.horizon_label) FROM claim_scores s WHERE s.unit_id=u.id), '[]') AS scores"
    )

    def browse_units(self, *, kind: str | None = None, creator_id: int | None = None,
                     tag: str | None = None, symbol: str | None = None,
                     q: str | None = None, limit: int = 200) -> list[dict]:
        """跨内容单元浏览（知识库的判断/方法/认知/标签/标的入口 + ⌘K 全文检索）。"""
        cond, params = [], []
        if kind:
            cond.append("u.kind=%s"); params.append(kind)
        if creator_id:
            cond.append("u.creator_id=%s"); params.append(creator_id)
        if tag:
            cond.append("%s = ANY(u.tags)"); params.append(tag)
        if symbol:
            cond.append("u.payload->>'asset_symbol'=%s"); params.append(symbol)
        if q:
            cond.append("(u.quote ILIKE %s OR u.payload::text ILIKE %s)")
            params.extend([f"%{q}%", f"%{q}%"])
        where = ("WHERE " + " AND ".join(cond)) if cond else ""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT u.*, cr.name AS creator, c.title AS content_title, "
                f"{self._UNIT_SCORES_AGG} "
                f"FROM knowledge_units u JOIN creators cr ON cr.id=u.creator_id "
                f"JOIN contents c ON c.id=u.content_id {where} "
                f"ORDER BY u.published_at DESC NULLS LAST, u.id DESC LIMIT %s",
                (*params, limit),
            ).fetchall()

    def unit_detail(self, unit_id: int) -> dict | None:
        """单元详情页：单元 + 信源/内容元信息 + 全部评分行。"""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT u.*, cr.name AS creator, c.title AS content_title, c.url AS content_url, "
                f"{self._UNIT_SCORES_AGG} "
                f"FROM knowledge_units u JOIN creators cr ON cr.id=u.creator_id "
                f"JOIN contents c ON c.id=u.content_id WHERE u.id=%s", (unit_id,),
            ).fetchone()

    def recent_scores(self, *, days: int = 14, limit: int = 100) -> list[dict]:
        """新到期评分流（今日页）：按评分落库时刻倒序，带单元与信源摘要。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT s.id, s.unit_id, s.horizon_label, s.outcome, s.realized, "
                "s.eval_ts, s.created_at AS scored_at, "
                "u.kind, u.quote, u.payload, u.published_at, u.creator_id, u.content_id, "
                "cr.name AS creator, c.title AS content_title "
                "FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                "JOIN creators cr ON cr.id=u.creator_id JOIN contents c ON c.id=u.content_id "
                "WHERE s.created_at >= now() - make_interval(days => %s) "
                "ORDER BY s.created_at DESC, s.id DESC LIMIT %s", (days, limit),
            ).fetchall()

    def verification_queue(self, *, days: int = 14, limit: int = 120) -> dict:
        """验证中心的行动队列。

        评分行只代表已发生的判定；即将到期的 Claim 需从冻结的 eval_ladder
        反查，不能把“尚未写入评分”误报成没有工作。这是纯读取视图，不改变
        评分器或任何状态。
        """
        with self.pool.connection() as conn:
            due = conn.execute("""
                SELECT u.id AS unit_id, u.quote, u.payload, u.published_at,
                  u.ref_price_at_publish, cr.name AS creator, c.title AS content_title,
                  ladder.label AS horizon_label
                FROM knowledge_units u
                JOIN creators cr ON cr.id=u.creator_id
                JOIN contents c ON c.id=u.content_id
                CROSS JOIN LATERAL jsonb_array_elements_text(
                  COALESCE(u.payload->'scoring_spec'->'eval_ladder', '[]'::jsonb)
                ) AS ladder(label)
                WHERE u.kind='claim'
                  AND ladder.label ~ '^\\d{4}-\\d{2}-\\d{2}$'
                  AND ladder.label::date BETWEEN current_date AND current_date + %s
                  AND NOT EXISTS (
                    SELECT 1 FROM claim_scores s
                    WHERE s.unit_id=u.id AND s.horizon_label=ladder.label
                  )
                ORDER BY ladder.label, u.published_at DESC NULLS LAST
                LIMIT %s
            """, (days, limit)).fetchall()
            scores = conn.execute("""
                SELECT s.id AS score_id, s.unit_id, s.horizon_label, s.outcome, s.realized,
                  s.eval_ts, s.created_at AS scored_at, u.quote, u.payload, u.published_at,
                  u.ref_price_at_publish, cr.name AS creator, c.title AS content_title
                FROM claim_scores s
                JOIN knowledge_units u ON u.id=s.unit_id
                JOIN creators cr ON cr.id=u.creator_id
                JOIN contents c ON c.id=u.content_id
                ORDER BY s.created_at DESC, s.id DESC
                LIMIT %s
            """, (limit,)).fetchall()

        verdicts = [s for s in scores if s["outcome"] in {"hit", "partial", "miss"}]
        unavailable = [s for s in scores if s["outcome"] in {
            "unpriceable", "condition_unverifiable",
        }]
        review = [s for s in scores if s["outcome"] in {"condition_not_met", "pending"}]
        return {
            "overview": {
                "due": len(due), "completed": len(verdicts), "unavailable": len(unavailable),
                "review": len(review),
            },
            "due": due,
            "recent": verdicts,
            "unavailable": unavailable,
            "review": review,
        }

    def verification_detail(self, score_id: int) -> dict | None:
        """一次已落库验证的不可变判定档案，含出处和受影响的知识节点。"""
        with self.pool.connection() as conn:
            row = conn.execute("""
                SELECT s.id AS score_id, s.unit_id, s.horizon_label, s.outcome, s.realized,
                  s.eval_ts, s.created_at AS scored_at, s.scorer_version,
                  u.quote, u.locator, u.payload, u.tags, u.published_at,
                  u.ref_price_at_publish, u.extractor_version,
                  cr.id AS creator_id, cr.name AS creator,
                  c.id AS content_id, c.title AS content_title, c.url AS content_url
                FROM claim_scores s
                JOIN knowledge_units u ON u.id=s.unit_id
                JOIN creators cr ON cr.id=u.creator_id
                JOIN contents c ON c.id=u.content_id
                WHERE s.id=%s
            """, (score_id,)).fetchone()
            if row is None:
                return None
            row["nodes"] = conn.execute("""
                SELECT n.id, n.title, n.status, n.kind, a.relation, a.note
                FROM node_attestations a JOIN knowledge_nodes n ON n.id=a.node_id
                WHERE a.unit_id=%s ORDER BY n.id
            """, (row["unit_id"],)).fetchall()
        return row

    def units(self, *, kind: str | None = None, creator_id: int | None = None,
              limit: int = 100) -> list[dict]:
        cond, params = [], []
        if kind:
            cond.append("kind=%s")
            params.append(kind)
        if creator_id:
            cond.append("creator_id=%s")
            params.append(creator_id)
        where = ("WHERE " + " AND ".join(cond)) if cond else ""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT * FROM knowledge_units {where} ORDER BY published_at DESC NULLS LAST "
                f"LIMIT %s", (*params, limit),
            ).fetchall()
