"""知识引擎持久化（独立库 fanisl_knowledge）。

L0 contents 追加式不可变（原文永存，下游全部可重放）；L1 units 带 extractor_version
双版本戳；(content_id, extractor_version) 在 extraction_runs 上唯一 = 重跑出新行不覆盖。
"""

from __future__ import annotations

import hashlib

from psycopg.types.json import Json
from psycopg_pool import ConnectionPool

from .models import KnowledgeUnit

_SCHEMA = """
CREATE TABLE IF NOT EXISTS creators (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    lang       TEXT NOT NULL DEFAULT 'zh',
    focus      TEXT,                 -- 擅长资产/主题（自由文本）
    notes      TEXT,
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS creator_handles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT NOT NULL REFERENCES creators(id) ON DELETE CASCADE,
    platform   TEXT NOT NULL,        -- youtube|rss|x|telegram|manual…
    handle     TEXT NOT NULL,        -- @handle / channel_id / feed url
    url        TEXT,
    added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (platform, handle)
);

CREATE TABLE IF NOT EXISTS contents (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id   BIGINT NOT NULL REFERENCES creators(id) ON DELETE CASCADE,
    platform     TEXT NOT NULL,
    url          TEXT,
    content_type TEXT NOT NULL,      -- video|article|post|podcast|manual
    title        TEXT,
    published_at TIMESTAMPTZ,        -- 平台声称的发布时刻（PIT 锚点）
    fetched_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    lang         TEXT,
    raw          TEXT NOT NULL,      -- 全文/转录，永存不改
    dedup_hash   TEXT NOT NULL UNIQUE,
    triage       JSONB,              -- L0 门卫结果
    status       TEXT NOT NULL DEFAULT 'new',  -- new|triaged|awaiting_manual|extracted|skipped
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_contents_status ON contents(status, published_at);

CREATE TABLE IF NOT EXISTS extraction_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id        BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    extractor_version TEXT NOT NULL,
    model             TEXT,
    n_units           INT NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (content_id, extractor_version)
);

CREATE TABLE IF NOT EXISTS knowledge_units (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            BIGINT NOT NULL REFERENCES extraction_runs(id) ON DELETE CASCADE,
    content_id        BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    creator_id        BIGINT NOT NULL,
    published_at      TIMESTAMPTZ,          -- 冗余自 content（PIT 锚点）
    kind              TEXT NOT NULL,        -- claim|method|concept
    quote             TEXT NOT NULL,
    locator           TEXT,
    extractor_version TEXT NOT NULL,
    model             TEXT,
    payload           JSONB NOT NULL,
    tags              TEXT[] NOT NULL DEFAULT '{}',
    ref_price_at_publish DOUBLE PRECISION,  -- claim：发布时刻市价（pit.asof 补）
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_units_kind ON knowledge_units(kind, creator_id, published_at);

CREATE TABLE IF NOT EXISTS claim_scores (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id        BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    eval_ts        TIMESTAMPTZ NOT NULL,
    horizon_label  TEXT NOT NULL,           -- 阶梯标签（如 '2026-08-31' / '30d'）
    outcome        TEXT NOT NULL,           -- hit|miss|partial|condition_not_met|condition_unverifiable|unpriceable|pending
    realized       JSONB,                   -- 实际收益/触及价等
    scorer_version TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (unit_id, horizon_label, scorer_version)
);

CREATE TABLE IF NOT EXISTS spot_checks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id    BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    verdict    TEXT NOT NULL,               -- faithful|unfaithful|unclear
    note       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""


def dedup_hash(raw: str) -> str:
    return hashlib.sha256(raw.strip().encode()).hexdigest()[:32]


class KnowledgeStore:
    def __init__(self, pool: ConnectionPool) -> None:
        self.pool = pool
        with pool.connection() as conn:
            conn.execute(_SCHEMA)

    # --- 信源 -------------------------------------------------------------

    def ensure_creator(self, name: str, *, lang: str = "zh", focus: str | None = None,
                       notes: str | None = None) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO creators(name, lang, focus, notes) VALUES (%s,%s,%s,%s) "
                "ON CONFLICT (name) DO UPDATE SET lang=EXCLUDED.lang RETURNING id",
                (name, lang, focus, notes),
            ).fetchone()
        return int(row["id"])

    def ensure_handle(self, creator_id: int, platform: str, handle: str,
                      url: str | None = None) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO creator_handles(creator_id, platform, handle, url) "
                "VALUES (%s,%s,%s,%s) ON CONFLICT (platform, handle) DO UPDATE "
                "SET url=EXCLUDED.url RETURNING id",
                (creator_id, platform, handle, url),
            ).fetchone()
        return int(row["id"])

    def creators(self) -> list[dict]:
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT c.*, COALESCE(json_agg(json_build_object('platform', h.platform, "
                "'handle', h.handle, 'url', h.url)) FILTER (WHERE h.id IS NOT NULL), '[]') AS handles "
                "FROM creators c LEFT JOIN creator_handles h ON h.creator_id=c.id "
                "GROUP BY c.id ORDER BY c.id",
            ).fetchall()
        return rows

    # --- L0 内容（追加式）--------------------------------------------------

    def upsert_content(self, creator_id: int, *, platform: str, url: str | None,
                       content_type: str, title: str | None, published_at,
                       raw: str, lang: str | None = None) -> tuple[int, bool]:
        """按 dedup_hash 幂等插入。返回 (content_id, 是否新建)。已存在时不改原文。"""
        h = dedup_hash(raw)
        with self.pool.connection() as conn:
            row = conn.execute("SELECT id FROM contents WHERE dedup_hash=%s", (h,)).fetchone()
            if row:
                return int(row["id"]), False
            row = conn.execute(
                "INSERT INTO contents(creator_id, platform, url, content_type, title, "
                "published_at, lang, raw, dedup_hash) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s) "
                "RETURNING id",
                (creator_id, platform, url, content_type, title, published_at, lang, raw, h),
            ).fetchone()
        return int(row["id"]), True

    def set_triage(self, content_id: int, triage: dict, status: str) -> None:
        with self.pool.connection() as conn:
            conn.execute("UPDATE contents SET triage=%s, status=%s WHERE id=%s",
                         (Json(triage), status, content_id))

    def set_status(self, content_id: int, status: str) -> None:
        with self.pool.connection() as conn:
            conn.execute("UPDATE contents SET status=%s WHERE id=%s", (status, content_id))

    def contents_by_status(self, status: str, *, limit: int = 50) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM contents WHERE status=%s ORDER BY published_at NULLS LAST "
                "LIMIT %s", (status, limit),
            ).fetchall()

    def get_content(self, content_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT c.*, cr.name AS creator FROM contents c "
                "JOIN creators cr ON cr.id=c.creator_id WHERE c.id=%s", (content_id,),
            ).fetchone()

    def list_contents(self, *, status: str | None = None, limit: int = 200) -> list[dict]:
        """内容列表（不含 raw 全文，带信源名/字数/已提取单元数）——前端列表页用。"""
        cond = "WHERE c.status=%s" if status else ""
        params: tuple = (status, limit) if status else (limit,)
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT c.id, c.creator_id, cr.name AS creator, c.platform, c.url, "
                f"c.content_type, c.title, c.published_at, c.fetched_at, c.lang, c.status, "
                f"length(c.raw) AS raw_len, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id) AS n_units "
                f"FROM contents c JOIN creators cr ON cr.id=c.creator_id {cond} "
                f"ORDER BY c.published_at DESC NULLS LAST, c.id DESC LIMIT %s", params,
            ).fetchall()

    # --- L1 提取（版本化重放）----------------------------------------------

    def record_extraction(self, content_id: int, *, extractor_version: str,
                          model: str | None, units: list[KnowledgeUnit],
                          ref_prices: dict[int, float] | None = None) -> list[int]:
        """一次提取运行：runs 上 (content_id, version) 唯一；重复运行报错（换版本号重跑）。
        ref_prices: 单元下标 → 发布时刻市价（claim 用）。返回 unit id 列表。"""
        c = self.get_content(content_id)
        if c is None:
            raise ValueError(f"content {content_id} 不存在")
        ids: list[int] = []
        with self.pool.connection() as conn:
            run = conn.execute(
                "INSERT INTO extraction_runs(content_id, extractor_version, model, n_units) "
                "VALUES (%s,%s,%s,%s) RETURNING id",
                (content_id, extractor_version, model, len(units)),
            ).fetchone()
            for i, u in enumerate(units):
                row = conn.execute(
                    "INSERT INTO knowledge_units(run_id, content_id, creator_id, published_at, "
                    "kind, quote, locator, extractor_version, model, payload, tags, "
                    "ref_price_at_publish) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) "
                    "RETURNING id",
                    (run["id"], content_id, c["creator_id"], c["published_at"], u.kind,
                     u.quote, u.locator, extractor_version, model, Json(u.payload), u.tags,
                     (ref_prices or {}).get(i)),
                ).fetchone()
                ids.append(int(row["id"]))
            conn.execute("UPDATE contents SET status='extracted' WHERE id=%s", (content_id,))
        return ids

    def units(self, *, kind: str | None = None, creator_id: int | None = None,
              limit: int = 100) -> list[dict]:
        cond, params = [], []
        if kind:
            cond.append("kind=%s")
            params.append(kind)
        if creator_id:
            cond.append("creator_id=%s")
            params.append(creator_id)
        where = ("WHERE " + " AND ".join(cond)) if cond else ""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT * FROM knowledge_units {where} ORDER BY published_at DESC NULLS LAST "
                f"LIMIT %s", (*params, limit),
            ).fetchall()
