import type { KnowledgeNode, KnowledgeStats } from './types'

export const previewStats: KnowledgeStats = {
  nodes: 105,
  contents: 18,
  units: 247,
  creators: 2,
  corroborated: 9,
}

export const previewNodes: KnowledgeNode[] = [
  {
    id: 1,
    kind: 'concept',
    title: '消息当噪音，按价格行为决策',
    canonical: '不以消息面与地缘政治作决策依据，一律当噪音处理，通过价格行为读资金动向——越预判消息越容易被反复打脸。',
    status: 'corroborated',
    tags: ['price-action', 'risk-mgmt'],
    notes: 'Andy 跨两期重复：屏蔽消息噪音的语境不同，但命题一致——消息面是噪音，价格行为才是决策依据。',
    n_attest: 2,
    n_creators: 1,
    n_contents: 2,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 2,
    kind: 'concept',
    title: 'K型经济：消费由高收入主导',
    canonical: '美国当前为 K 型经济：消费由高收入人群主导，高工资增速与股市财富效应使整体消费韧性强于直觉；油价冲击是其压力测试。',
    status: 'corroborated',
    tags: ['consumer', 'macro-data', 'ai-capex'],
    notes: '跨源印证：美投君以数据论证，Andy 转述机构共识并扩展到美中都是 K 型经济。',
    n_attest: 2,
    n_creators: 2,
    n_contents: 2,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 3,
    kind: 'concept',
    title: '高位分批止盈并切换风格',
    canonical: '高位用保护性对冲或分批止盈锁定拥挤板块利润，再切换风格、分散到慢周期赛道——这是本轮吃到半导体行情者更成熟的处理方式。',
    status: 'corroborated',
    tags: ['rotation', 'risk-mgmt', 'position-sizing'],
    notes: '同一实践的两面：退出节奏与再配置方向处在高度重叠的 AI、半导体拥挤语境中，因此归并为一个节点。',
    n_attest: 2,
    n_creators: 1,
    n_contents: 2,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 4,
    kind: 'concept',
    title: '预期打满板块：容错极低与踩踏循环',
    canonical: '预期交易过满的板块容错极低：小利空引发踩踏离场，低位资金承接拖起，追高动能不足，最终形成宽幅震荡。',
    status: 'corroborated',
    tags: ['market-breadth', 'memory-storage', 'psychology'],
    notes: '两次表述使用同一个三星财报案例；后一次补全了“踩踏—承接—拖起—动能不足”的循环链条。',
    n_attest: 2,
    n_creators: 1,
    n_contents: 2,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 5,
    kind: 'concept',
    title: 'AI时代软件收费：席位→按量→按结果',
    canonical: '企业从无脑投入 AI 转向严格核算 ROI：席位制因裁员减席位和 token 成本自担而失效，按量收费只是中间形态，终局是按结果收费。',
    status: 'corroborated',
    tags: ['software', 'ai-capex'],
    notes: '观点演进：2026-05-31 认为按量收费是唯一出路；2026-06-21 修正为按量只是中间形态，终局是按结果收费。',
    n_attest: 2,
    n_creators: 1,
    n_contents: 2,
    first_seen: '2026-05-31T20:00:00+08:00',
    last_seen: '2026-06-21T20:00:00+08:00',
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 6,
    kind: 'concept',
    title: '不择时：以风险管理替代进出场',
    canonical: '不做无法精准预判的择时：短期做好风险应对，不被波动赶下牌桌，择机买入优质公司并等待风险释放。',
    status: 'corroborated',
    tags: ['risk-mgmt', 'psychology'],
    notes: '美投君跨两期重复：先提出不择时与择机买入的原则，后在风险期重申“留在市场上”。',
    n_attest: 2,
    n_creators: 1,
    n_contents: 2,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 7,
    kind: 'method',
    title: '黄金叙事切换日的识别',
    canonical: '等待黄金逆实际利率与流动性逻辑独立走强：消息与价格共振，或黄金相对股市明显抗跌。信号日前保持耐心，出现后再考虑中长期进攻。',
    status: 'corroborated',
    tags: ['xauusd', 'macro-data', 'rotation', 'price-action'],
    notes: '同一识别目标的两个观察变体：消息面共振，以及黄金与股市的相对强弱。',
    n_attest: 2,
    n_creators: 1,
    n_contents: 2,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 8,
    kind: 'method',
    title: '长债收益率两小时反转信号',
    canonical: '30 年期收益率冲击 5% 等关键位时，观察两小时级别的高位十字星加向下反包，或强度明显超过前阳线的大阴线；确认前不逆势抄底。',
    status: 'corroborated',
    tags: ['us30y', 'ndx', 'macro-data', 'price-action'],
    notes: '同一方法的两个形态变体被归并，规则保留两种确认方式以及三个历史信号日实例。',
    n_attest: 2,
    n_creators: 1,
    n_contents: 2,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 9,
    kind: 'claim',
    title: '标普500 2026年底 8200 点',
    canonical: '标普 500 的 2026 年底目标为 8200 点，采用 target_close ±2% 判定；该目标在 6 月与 7 月被两次公开重申。',
    status: 'corroborated',
    tags: ['spx'],
    notes: '这是 Claim 允许归并的唯一情形：同标的、同目标、同期限的字面重申。评分时点为 2026-12-31。',
    n_attest: 2,
    n_creators: 1,
    n_contents: 2,
    first_seen: '2026-06-08T20:00:00+08:00',
    last_seen: '2026-07-05T20:00:00+08:00',
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 10,
    kind: 'concept',
    title: '半导体＝数字地租（周期已破）',
    canonical: '半导体已从消费电子驱动的周期行业转为数字文明的物理底座：需求侧算力增长远快于供给侧扩产，剪刀差长期化。',
    status: 'active',
    tags: ['semiconductor-cycle', 'ai-capex'],
    notes: '与“芯片板块的周期性涨法”构成跨源对立命题：周期已经被打破，还是传统周期仍在。',
    n_attest: 1,
    n_creators: 1,
    n_contents: 1,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
  {
    id: 11,
    kind: 'concept',
    title: '芯片板块的周期性涨法',
    canonical: '芯片板块仍是典型周期行业：复苏确认后快速上涨，随后盘整消化估值，再进入下一轮上涨，呈台阶式推进。',
    status: 'active',
    tags: ['semiconductor-cycle', 'market-breadth'],
    notes: '与“半导体＝数字地租”构成跨源对立命题，二者不归并，差异保留到发现层。',
    n_attest: 1,
    n_creators: 1,
    n_contents: 1,
    first_seen: null,
    last_seen: null,
    hit: 0,
    partial: 0,
    miss: 0,
  },
]
