"""知识引擎持久化（独立库 fanisl_knowledge）。

L0 contents 追加式不可变（原文永存，下游全部可重放）；L1 units 带 extractor_version
双版本戳；(content_id, extractor_version) 在 extraction_runs 上唯一 = 重跑出新行不覆盖。
"""

from __future__ import annotations

import hashlib
import re

from psycopg.types.json import Json
from psycopg_pool import ConnectionPool

from .. import assets
from .models import KnowledgeUnit

_SCHEMA = """
CREATE TABLE IF NOT EXISTS creators (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    lang       TEXT NOT NULL DEFAULT 'zh',
    focus      TEXT,                 -- 擅长资产/主题（自由文本）
    notes      TEXT,
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS creator_handles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT NOT NULL REFERENCES creators(id) ON DELETE CASCADE,
    platform   TEXT NOT NULL,        -- youtube|rss|x|telegram|manual…
    handle     TEXT NOT NULL,        -- @handle / channel_id / feed url
    url        TEXT,
    added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (platform, handle)
);

CREATE TABLE IF NOT EXISTS contents (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id   BIGINT NOT NULL REFERENCES creators(id) ON DELETE CASCADE,
    platform     TEXT NOT NULL,
    url          TEXT,
    content_type TEXT NOT NULL,      -- video|article|post|podcast|manual
    title        TEXT,
    published_at TIMESTAMPTZ,        -- 平台声称的发布时刻（PIT 锚点）
    fetched_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    lang         TEXT,
    raw          TEXT NOT NULL,      -- 全文/转录，永存不改
    dedup_hash   TEXT NOT NULL UNIQUE,
    triage       JSONB,              -- L0 门卫结果
    status       TEXT NOT NULL DEFAULT 'new',  -- new|triaged|awaiting_manual|extracted|skipped
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_contents_status ON contents(status, published_at);
-- 摄取自哪个频道。一个信源可以有几个频道（美投君：@MeiTouJun 与 @MeiTouNews，2026-09-24），
-- 摄取缺口要按频道算——按信源算时，一个频道刚更新就会把另一个频道的缺口遮住。
-- 老内容回填：只回填该平台上只登记了一个频道的信源，多频道的归属从 creator 推不出来。
ALTER TABLE contents ADD COLUMN IF NOT EXISTS handle TEXT;
UPDATE contents c SET handle = h.handle FROM creator_handles h
 WHERE c.handle IS NULL AND h.creator_id = c.creator_id AND h.platform = c.platform
   AND (SELECT count(*) FROM creator_handles h2
         WHERE h2.creator_id = c.creator_id AND h2.platform = c.platform) = 1;

-- 同一条 content 可以有多版提取（v1 / v2 …）全部留库不删，但**只有一版参与下游统计**：
-- 否则升版重提之后，联赛表/含糊率/抽查覆盖率会把同一期内容数两遍。谁是当前那一版由
-- status 说了算（active|superseded），换版走 activate_run，不靠"取最新"之类的隐式规则。
CREATE TABLE IF NOT EXISTS extraction_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id        BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    extractor_version TEXT NOT NULL,
    model             TEXT,
    n_units           INT NOT NULL DEFAULT 0,
    status            TEXT NOT NULL DEFAULT 'active',   -- active|superseded
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (content_id, extractor_version)
);
ALTER TABLE extraction_runs ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
-- 一条 content 最多一个 active run（部分唯一索引；数据库层兜底，不靠调用方自觉）
CREATE UNIQUE INDEX IF NOT EXISTS uq_runs_one_active
    ON extraction_runs(content_id) WHERE status = 'active';

CREATE TABLE IF NOT EXISTS knowledge_units (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            BIGINT NOT NULL REFERENCES extraction_runs(id) ON DELETE CASCADE,
    content_id        BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    creator_id        BIGINT NOT NULL,
    published_at      TIMESTAMPTZ,          -- 冗余自 content（PIT 锚点）
    kind              TEXT NOT NULL,        -- claim|method|concept
    quote             TEXT NOT NULL,
    locator           TEXT,
    extractor_version TEXT NOT NULL,
    model             TEXT,
    payload           JSONB NOT NULL,
    tags              TEXT[] NOT NULL DEFAULT '{}',
    ref_price_at_publish DOUBLE PRECISION,  -- claim：发布时刻市价（pit.asof 补）
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_units_kind ON knowledge_units(kind, creator_id, published_at);

CREATE TABLE IF NOT EXISTS claim_scores (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id        BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    eval_ts        TIMESTAMPTZ NOT NULL,
    horizon_label  TEXT NOT NULL,           -- 阶梯标签（如 '2026-08-31' / '30d'）
    outcome        TEXT NOT NULL,           -- hit|miss|partial|condition_not_met|condition_unverifiable|unpriceable|pending
    realized       JSONB,                   -- 实际收益/触及价等
    scorer_version TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (unit_id, horizon_label, scorer_version)
);

CREATE TABLE IF NOT EXISTS spot_checks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id    BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    verdict    TEXT NOT NULL,               -- faithful|unfaithful|unclear
    note       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 视觉笔记的像素凭据：笔记记"画面上写了 63/61/63"，帧让这句话可核。视频被删后
-- 也只剩这两样。文件本体在 data_export/keyframes/（gitignore，可按本表重抓）。
CREATE TABLE IF NOT EXISTS keyframes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
    ts_s       INT NOT NULL,               -- 视频内秒偏移（取自视觉笔记时间戳）
    kind       TEXT,                       -- chart|table|text_slide|other
    note       TEXT,                       -- 该时刻的视觉笔记原文（核对对象）
    path       TEXT NOT NULL,              -- 相对 data_export/ 的路径
    height     INT NOT NULL,
    bytes      INT,
    source     TEXT NOT NULL,              -- 提帧通道 ytdlp:<client>（墙再动时可回看）
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (content_id, ts_s)
);

-- 单元核查：站上用户对某条单元提出异议，知识席位（Claude 会话）答复、修改、复盘。
-- **不并入 spot_checks**：那张表是 extraction-guide §10 的随机抽样，核查对象是用户挑出来的，
-- 混进去会让抽查的忠实率失去随机性。答复只走 CLI（knowledge/review.py），网站写不了——
-- 站上无法冒充知识席位发言。
CREATE TABLE IF NOT EXISTS unit_reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id    BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    category   TEXT NOT NULL,                 -- quote|grade|scoring|asset|statement|other
    status     TEXT NOT NULL DEFAULT 'open',  -- open 待知识席位答复 | answered 待用户确认 | closed
    created_by TEXT NOT NULL,                 -- 登录用户名（API 从会话取，不信请求体）
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS unit_reviews_by_status ON unit_reviews (status, updated_at);
CREATE INDEX IF NOT EXISTS unit_reviews_by_unit ON unit_reviews (unit_id);

CREATE TABLE IF NOT EXISTS unit_review_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id  BIGINT NOT NULL REFERENCES unit_reviews(id) ON DELETE CASCADE,
    role       TEXT NOT NULL,                 -- reviewer 站上用户 | extractor 知识席位
    author     TEXT NOT NULL,
    body       TEXT NOT NULL,
    resolution JSONB,                         -- 仅 extractor：{outcome, root_cause, sweep, followup}
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS unit_review_messages_by_review ON unit_review_messages (review_id, id);

-- 单元原地修改的留痕。单元是评分争议的仲裁依据，改了必须能回看改前是什么——此前的
-- 修改只能靠提交信息追溯。data_export 下的 JSON 是入库那一刻的快照、不跟着改；同
-- (content_id, extractor_version) 重复导入会被拒，所以修改不会被重新导入冲掉。
CREATE TABLE IF NOT EXISTS unit_amendments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id    BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    review_id  BIGINT REFERENCES unit_reviews(id) ON DELETE SET NULL,
    before     JSONB NOT NULL,                -- {quote, payload, tags}
    after      JSONB NOT NULL,
    reason     TEXT NOT NULL,
    author     TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS unit_amendments_by_unit ON unit_amendments (unit_id, id);

-- 作废的评分：整行原样搬到这里、从 claim_scores 移走，所有统计自动不再计它。两种：
--   rescore=false  本不该存在的评分时点（期限判错，多出来的阶梯被评了），评分器不再评它；
--   rescore=true   评分器没按冻结的 success_def 执行（机器配置漏了条件等），配置修好后重评。
CREATE TABLE IF NOT EXISTS claim_score_voids (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id        BIGINT NOT NULL REFERENCES knowledge_units(id) ON DELETE CASCADE,
    horizon_label  TEXT NOT NULL,
    scorer_version TEXT NOT NULL,
    score          JSONB NOT NULL,                -- 作废前 claim_scores 那一行
    reason         TEXT NOT NULL,
    author         TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE claim_score_voids ADD COLUMN IF NOT EXISTS rescore BOOLEAN NOT NULL DEFAULT false;
-- 同一时点可以先重评、后来又作废，不能唯一
ALTER TABLE claim_score_voids DROP CONSTRAINT IF EXISTS claim_score_voids_unit_id_horizon_label_scorer_version_key;
"""


# 下游统计只看当前生效那一版提取。凡是**数单元/算比例/挑待办**的查询都要带上它；
# 按 unit_id 单查、或从 claim_scores 反查（已被 unit_id 限定）的不用带。
# 别名固定为 u，用法：f"... FROM knowledge_units u WHERE ... AND {ACTIVE_RUN}"
ACTIVE_RUN = ("EXISTS (SELECT 1 FROM extraction_runs r "
              "WHERE r.id = u.run_id AND r.status = 'active')")

# 同理，重转录后的旧稿（contents.status='superseded'）不该进任何"有几期内容"的计数。
# 别名固定为 c。**去重前置闸不能带它**（upsert_content 的 dedup_hash 查询、
# content_url_exists）——那两处正需要看见旧稿，否则同一个视频会被反复付费转录。
LIVE_CONTENT = "c.status <> 'superseded'"


def dedup_hash(raw: str) -> str:
    return hashlib.sha256(raw.strip().encode()).hexdigest()[:32]


def quote_in_source(raw: str, quote: str) -> bool:
    """quote 必须逐字出自原文：空白归一后是子串。导入与单元修改共用这一条规则。"""
    return re.sub(r"\s+", "", quote) in re.sub(r"\s+", "", raw)


def amendment_changes(before: dict, after: dict) -> list[str]:
    """一次修改动了哪些字段（quote / tags / payload.<键>），供 CLI 与前端直接展示。"""
    out = [k for k in ("quote", "tags") if before.get(k) != after.get(k)]
    bp, ap = before.get("payload") or {}, after.get("payload") or {}
    return out + [f"payload.{k}" for k in sorted(set(bp) | set(ap)) if bp.get(k) != ap.get(k)]


class ReviewConflict(Exception):
    """核查或单元的当前状态不允许这个操作（例如答复一条不在 open 的核查）。API 映射 409。

    约定：输入不合法抛 ValueError（400），对象不存在抛 LookupError（404）。
    """


class KnowledgeStore:
    def __init__(self, pool: ConnectionPool) -> None:
        self.pool = pool
        with pool.connection() as conn:
            conn.execute(_SCHEMA)

    # --- 信源 -------------------------------------------------------------

    def ensure_creator(self, name: str, *, lang: str = "zh", focus: str | None = None,
                       notes: str | None = None) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO creators(name, lang, focus, notes) VALUES (%s,%s,%s,%s) "
                "ON CONFLICT (name) DO UPDATE SET lang=EXCLUDED.lang RETURNING id",
                (name, lang, focus, notes),
            ).fetchone()
        return int(row["id"])

    def ensure_handle(self, creator_id: int, platform: str, handle: str,
                      url: str | None = None) -> int:
        with self.pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO creator_handles(creator_id, platform, handle, url) "
                "VALUES (%s,%s,%s,%s) ON CONFLICT (platform, handle) DO UPDATE "
                "SET url=EXCLUDED.url RETURNING id",
                (creator_id, platform, handle, url),
            ).fetchone()
        return int(row["id"])

    def creators(self) -> list[dict]:
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT c.*, COALESCE(json_agg(json_build_object('platform', h.platform, "
                "'handle', h.handle, 'url', h.url)) FILTER (WHERE h.id IS NOT NULL), '[]') AS handles "
                "FROM creators c LEFT JOIN creator_handles h ON h.creator_id=c.id "
                "GROUP BY c.id ORDER BY c.id",
            ).fetchall()
        return rows

    # --- L0 内容（追加式）--------------------------------------------------

    def upsert_content(self, creator_id: int, *, platform: str, url: str | None,
                       content_type: str, title: str | None, published_at,
                       raw: str, lang: str | None = None,
                       triage: dict | None = None,
                       handle: str | None = None) -> tuple[int, bool]:
        """按 dedup_hash 幂等插入。返回 (content_id, 是否新建)。已存在时不改原文。

        triage 记转录出处（model/channel）。2026-08 的教训：lite 档模型会改写数字，
        事后想圈出受影响的内容却发现库里没留通道记录，只能靠会话日志回溯。
        handle 是摄取自哪个频道，每日摄取按它算缺口（见 daily.ingest_since_days）。
        """
        h = dedup_hash(raw)
        with self.pool.connection() as conn:
            row = conn.execute("SELECT id FROM contents WHERE dedup_hash=%s", (h,)).fetchone()
            if row:
                return int(row["id"]), False
            row = conn.execute(
                "INSERT INTO contents(creator_id, platform, url, content_type, title, "
                "published_at, lang, raw, dedup_hash, triage, handle) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                (creator_id, platform, url, content_type, title, published_at, lang, raw, h,
                 Json(triage) if triage else None, handle),
            ).fetchone()
        return int(row["id"]), True

    def content_url_exists(self, url: str) -> bool:
        """按 URL 判存（批量回填跳过已转录的视频，省 Gemini 开销；raw 哈希去重之外的前置闸）。"""
        with self.pool.connection() as conn:
            return conn.execute("SELECT 1 FROM contents WHERE url=%s LIMIT 1", (url,)).fetchone() is not None

    def set_triage(self, content_id: int, triage: dict, status: str) -> None:
        with self.pool.connection() as conn:
            conn.execute("UPDATE contents SET triage=%s, status=%s WHERE id=%s",
                         (Json(triage), status, content_id))

    def set_status(self, content_id: int, status: str) -> None:
        with self.pool.connection() as conn:
            conn.execute("UPDATE contents SET status=%s WHERE id=%s", (status, content_id))

    def contents_by_status(self, status: str, *, limit: int = 50) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM contents WHERE status=%s ORDER BY published_at NULLS LAST "
                "LIMIT %s", (status, limit),
            ).fetchall()

    def get_content(self, content_id: int) -> dict | None:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT c.*, cr.name AS creator FROM contents c "
                "JOIN creators cr ON cr.id=c.creator_id WHERE c.id=%s", (content_id,),
            ).fetchone()

    def list_contents(self, *, status: str | None = None, limit: int = 200) -> list[dict]:
        """内容列表（不含 raw 全文，带信源名/字数/单元构成/评分摘要）——前端列表页用。

        默认排除 superseded：重转录后的旧稿是 L0 的历史记录（append-only 不删），但任何
        "这个信源有几期"的计数都不该把同一期算两遍。要看旧稿传 status='superseded'。
        """
        cond = "WHERE c.status=%s" if status else f"WHERE {LIVE_CONTENT}"
        params: tuple = (status, limit) if status else (limit,)
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT c.id, c.creator_id, cr.name AS creator, c.platform, c.url, "
                f"c.content_type, c.title, c.published_at, c.fetched_at, c.lang, c.status, "
                f"length(c.raw) AS raw_len, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id AND {ACTIVE_RUN}) AS n_units, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id AND u.kind='claim' AND {ACTIVE_RUN}) AS n_claims, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id AND u.kind='method' AND {ACTIVE_RUN}) AS n_methods, "
                f"(SELECT count(*) FROM knowledge_units u WHERE u.content_id=c.id AND u.kind='concept' AND {ACTIVE_RUN}) AS n_concepts, "
                f"(SELECT count(*) FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                f" WHERE u.content_id=c.id AND s.outcome='hit' AND {ACTIVE_RUN}) AS n_hit, "
                f"(SELECT count(*) FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                f" WHERE u.content_id=c.id AND s.outcome='partial' AND {ACTIVE_RUN}) AS n_partial, "
                f"(SELECT count(*) FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                f" WHERE u.content_id=c.id AND s.outcome='miss' AND {ACTIVE_RUN}) AS n_miss "
                f"FROM contents c JOIN creators cr ON cr.id=c.creator_id {cond} "
                f"ORDER BY c.published_at DESC NULLS LAST, c.id DESC LIMIT %s", params,
            ).fetchall()

    # --- 关键帧（视觉笔记的像素凭据）-----------------------------------------

    def record_keyframe(self, content_id: int, *, ts_s: int, path: str, height: int,
                        bytes_: int, source: str, kind: str | None = None,
                        note: str | None = None) -> None:
        """(content, ts) 唯一；重抓（如提高清晰度）覆盖同一行。"""
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO keyframes(content_id, ts_s, kind, note, path, height, bytes, source) "
                "VALUES (%s,%s,%s,%s,%s,%s,%s,%s) "
                "ON CONFLICT (content_id, ts_s) DO UPDATE SET "
                "path=EXCLUDED.path, height=EXCLUDED.height, bytes=EXCLUDED.bytes, "
                "source=EXCLUDED.source, kind=COALESCE(EXCLUDED.kind, keyframes.kind), "
                "note=COALESCE(EXCLUDED.note, keyframes.note)",
                (content_id, ts_s, kind, note, path, height, bytes_, source))

    def keyframes_for_content(self, content_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT * FROM keyframes WHERE content_id=%s ORDER BY ts_s", (content_id,),
            ).fetchall()

    def known_tags(self) -> set[str]:
        """生效版本里已经用过的全部标签——import 时的词表体检拿它当受控词表。

        用库而不是在代码里再写一份主题词表：extraction-guide §7 本身就是那份表，
        复制一遍必然漂移；而"这个词以前用过没有"恰好就是要问的问题。
        """
        with self.pool.connection() as conn:
            rows = conn.execute(
                f"SELECT DISTINCT unnest(u.tags) AS tag FROM knowledge_units u "
                f"WHERE {ACTIVE_RUN}").fetchall()
        return {r["tag"] for r in rows}

    def keyframe_seconds(self, content_id: int) -> set[int]:
        """已有帧的时间戳集合（回填幂等用）。"""
        with self.pool.connection() as conn:
            rows = conn.execute("SELECT ts_s FROM keyframes WHERE content_id=%s",
                                (content_id,)).fetchall()
        return {int(r["ts_s"]) for r in rows}

    def freeze_ref_price(self, unit_id: int, ref: float) -> bool:
        """把回查到的发布日参考价固化到单元上（只在还空着时写，绝不覆盖已有值）。

        ref_price_at_publish 是 PIT 锚点。提取时拿不到屏价就会空着，评分器只好回查
        发布日收盘——但 yfinance 给的是复权价，标的一拆股历史行情整体改写，同一条 claim
        的 +7/+30/+90 三个时点就会各自对着不同的参考价。第一次查到就钉死，之后不再漂。
        """
        with self.pool.connection() as conn:
            r = conn.execute(
                "UPDATE knowledge_units SET ref_price_at_publish=%s "
                "WHERE id=%s AND ref_price_at_publish IS NULL", (ref, unit_id))
        return r.rowcount > 0

    def activate_run(self, run_id: int) -> dict:
        """把某个 run 设为该 content 当前生效的那一版（其余转 superseded）。

        用于回退：v2 重提之后发现不如 v1，activate v1 的 run 即可，两版单元都还在库里。
        """
        with self.pool.connection() as conn:
            row = conn.execute("SELECT content_id, extractor_version FROM extraction_runs "
                               "WHERE id=%s", (run_id,)).fetchone()
            if row is None:
                raise ValueError(f"run {run_id} 不存在")
            conn.execute("UPDATE extraction_runs SET status='superseded' "
                         "WHERE content_id=%s AND id<>%s", (row["content_id"], run_id))
            conn.execute("UPDATE extraction_runs SET status='active' WHERE id=%s", (run_id,))
        return {"run_id": run_id, "content_id": row["content_id"],
                "extractor_version": row["extractor_version"]}

    def runs_for_content(self, content_id: int) -> list[dict]:
        """某内容的全部提取版本（含已被取代的），看得到才谈得上切换。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT id, extractor_version, model, n_units, status, created_at "
                "FROM extraction_runs WHERE content_id=%s ORDER BY created_at",
                (content_id,)).fetchall()

    def keyframe(self, keyframe_id: int) -> dict | None:
        """按 id 取单帧（读图端点用 id 而不是路径——路径来自库里，不给穿越的口子）。"""
        with self.pool.connection() as conn:
            return conn.execute("SELECT * FROM keyframes WHERE id=%s", (keyframe_id,)).fetchone()

    def keyframes_near(self, content_id: int, ts_s: int, *, window_s: int) -> list[dict]:
        """某内容里落在 [ts-window, ts+window] 的帧，按与 ts 的距离排序。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT *, abs(ts_s - %s) AS distance_s FROM keyframes "
                "WHERE content_id=%s AND ts_s BETWEEN %s AND %s ORDER BY distance_s, ts_s",
                (ts_s, content_id, ts_s - window_s, ts_s + window_s)).fetchall()

    def keyframe_span(self, content_id: int) -> tuple[int, int] | None:
        """该内容已有帧的时间跨度（判断 locator 是否越界用）。"""
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT min(ts_s) AS lo, max(ts_s) AS hi FROM keyframes WHERE content_id=%s",
                (content_id,)).fetchone()
        return (int(row["lo"]), int(row["hi"])) if row and row["lo"] is not None else None

    # --- L1 提取（版本化重放）----------------------------------------------

    def record_extraction(self, content_id: int, *, extractor_version: str,
                          model: str | None, units: list[KnowledgeUnit],
                          ref_prices: dict[int, float] | None = None) -> list[int]:
        """一次提取运行：runs 上 (content_id, version) 唯一；重复运行报错（换版本号重跑）。
        ref_prices: 单元下标 → 发布时刻市价（claim 用）。返回 unit id 列表。

        新 run 落库即接管 active，同一条 content 的旧 run 转 superseded（旧单元一条不删，
        只是不再进下游统计）。整件事在一个事务里：不允许出现"两版都 active"的中间态，
        部分唯一索引也会拦。要回退到旧版走 activate_run。
        """
        c = self.get_content(content_id)
        if c is None:
            raise ValueError(f"content {content_id} 不存在")
        ids: list[int] = []
        with self.pool.connection() as conn:
            conn.execute("UPDATE extraction_runs SET status='superseded' "
                         "WHERE content_id=%s AND status='active'", (content_id,))
            run = conn.execute(
                "INSERT INTO extraction_runs(content_id, extractor_version, model, n_units) "
                "VALUES (%s,%s,%s,%s) RETURNING id",
                (content_id, extractor_version, model, len(units)),
            ).fetchone()
            for i, u in enumerate(units):
                row = conn.execute(
                    "INSERT INTO knowledge_units(run_id, content_id, creator_id, published_at, "
                    "kind, quote, locator, extractor_version, model, payload, tags, "
                    "ref_price_at_publish) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) "
                    "RETURNING id",
                    (run["id"], content_id, c["creator_id"], c["published_at"], u.kind,
                     u.quote, u.locator, extractor_version, model, Json(u.payload), u.tags,
                     (ref_prices or {}).get(i)),
                ).fetchone()
                ids.append(int(row["id"]))
            conn.execute("UPDATE contents SET status='extracted' WHERE id=%s", (content_id,))
        return ids

    # --- L2 评分（到期机械评分的落库与视图）--------------------------------

    def score_exists(self, unit_id: int, horizon_label: str, scorer_version: str) -> bool:
        """评过、或评过又作废了，都算存在——作废的时点不许评分器再评回来（标了待重评的除外）。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT 1 FROM claim_scores WHERE unit_id=%s AND horizon_label=%s AND scorer_version=%s "
                "UNION ALL SELECT 1 FROM claim_score_voids WHERE unit_id=%s AND horizon_label=%s "
                "AND scorer_version=%s AND NOT rescore",
                (unit_id, horizon_label, scorer_version) * 2,
            ).fetchone() is not None

    def record_score(self, unit_id: int, *, eval_ts, horizon_label: str, outcome: str,
                     realized: dict, scorer_version: str) -> None:
        with self.pool.connection() as conn:
            conn.execute(
                "INSERT INTO claim_scores(unit_id, eval_ts, horizon_label, outcome, realized, "
                "scorer_version) VALUES (%s,%s,%s,%s,%s,%s) "
                "ON CONFLICT (unit_id, horizon_label, scorer_version) DO NOTHING",
                (unit_id, eval_ts, horizon_label, outcome, Json(realized), scorer_version))

    def scores_for_content(self, content_id: int) -> list[dict]:
        """某内容全部单元的评分行（前端详情页徽标用）。"""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT s.* FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                f"WHERE u.content_id=%s AND {ACTIVE_RUN} "
                f"ORDER BY s.unit_id, s.horizon_label", (content_id,),
            ).fetchall()

    def scoreboard(self) -> list[dict]:
        """信源联赛表：claim 战绩 + 含糊率（按已到期评分行统计；hit=1/partial=0.5 计入命中率）。"""
        with self.pool.connection() as conn:
            return conn.execute(f"""
                WITH c AS (
                    SELECT u.creator_id, u.id,
                           u.payload->>'verifiability' AS grade
                    FROM knowledge_units u WHERE u.kind='claim' AND {ACTIVE_RUN}
                ), s AS (
                    SELECT u.creator_id, s.outcome
                    FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id
                    WHERE {ACTIVE_RUN}
                )
                SELECT cr.id AS creator_id, cr.name,
                    (SELECT count(*) FROM c WHERE c.creator_id=cr.id)                          AS claims,
                    (SELECT count(*) FROM c WHERE c.creator_id=cr.id AND grade='D')            AS d_claims,
                    (SELECT count(*) FROM knowledge_units u
                      WHERE u.creator_id=cr.id AND u.kind='method' AND {ACTIVE_RUN})            AS methods,
                    (SELECT count(*) FROM knowledge_units u
                      WHERE u.creator_id=cr.id AND u.kind='concept' AND {ACTIVE_RUN})           AS concepts,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id
                      AND outcome IN ('hit','miss','partial'))                                 AS scored,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id AND outcome='hit')        AS hits,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id AND outcome='partial')    AS partials,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id AND outcome='miss')       AS misses,
                    (SELECT count(*) FROM s WHERE s.creator_id=cr.id
                      AND outcome='condition_not_met')                                         AS cond_not_met
                FROM creators cr ORDER BY cr.id""").fetchall()

    def units_for_content(self, content_id: int) -> list[dict]:
        """某内容当前生效那一版的全部单元（前端详情页用，claim 优先靠前，附评分行）。

        被取代的旧版提取仍在库里，但不从这里出——要看历史版本走 runs_for_content。
        """
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT u.*, COALESCE((SELECT json_agg(json_build_object("
                "'horizon_label', s.horizon_label, 'outcome', s.outcome, 'realized', s.realized) "
                "ORDER BY s.horizon_label) FROM claim_scores s WHERE s.unit_id=u.id), '[]') AS scores "
                f"FROM knowledge_units u WHERE u.content_id=%s AND {ACTIVE_RUN} "
                "ORDER BY (u.kind!='claim'), u.id", (content_id,),
            ).fetchall()

    def tags(self) -> list[dict]:
        """标签枢纽：受控词表的实际使用计数（按 kind 细分）。"""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT tag, count(*) AS n, "
                f"count(*) FILTER (WHERE u.kind='claim') AS n_claims, "
                f"count(*) FILTER (WHERE u.kind='method') AS n_methods, "
                f"count(*) FILTER (WHERE u.kind='concept') AS n_concepts "
                f"FROM knowledge_units u, unnest(u.tags) AS tag "
                f"WHERE {ACTIVE_RUN} "
                f"GROUP BY tag ORDER BY n DESC, tag").fetchall()

    _UNIT_SCORES_AGG = (
        "COALESCE((SELECT json_agg(json_build_object("
        "'horizon_label', s.horizon_label, 'outcome', s.outcome, 'realized', s.realized) "
        "ORDER BY s.horizon_label) FROM claim_scores s WHERE s.unit_id=u.id), '[]') AS scores"
    )

    def browse_units(self, *, kind: str | None = None, creator_id: int | None = None,
                     tag: str | None = None, symbol: str | None = None,
                     q: str | None = None, limit: int = 200) -> list[dict]:
        """跨内容单元浏览（知识库的判断/方法/认知/标签/标的入口 + ⌘K 全文检索）。"""
        cond, params = [ACTIVE_RUN], []
        if kind:
            cond.append("u.kind=%s"); params.append(kind)
        if creator_id:
            cond.append("u.creator_id=%s"); params.append(creator_id)
        if tag:
            cond.append("%s = ANY(u.tags)"); params.append(tag)
        if symbol:
            syms, tags = assets.symbol_variants(symbol)
            cond.append("(u.payload->>'asset_symbol' = ANY(%s) OR u.tags && %s::text[])")
            params.extend([syms, tags])
        if q:
            cond.append("(u.quote ILIKE %s OR u.payload::text ILIKE %s)")
            params.extend([f"%{q}%", f"%{q}%"])
        where = ("WHERE " + " AND ".join(cond)) if cond else ""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT u.*, cr.name AS creator, c.title AS content_title, "
                f"{self._UNIT_SCORES_AGG} "
                f"FROM knowledge_units u JOIN creators cr ON cr.id=u.creator_id "
                f"JOIN contents c ON c.id=u.content_id {where} "
                f"ORDER BY u.published_at DESC NULLS LAST, u.id DESC LIMIT %s",
                (*params, limit),
            ).fetchall()

    def unit_detail(self, unit_id: int) -> dict | None:
        """单元详情页：单元 + 信源/内容元信息 + 全部评分行。"""
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT u.*, cr.name AS creator, c.title AS content_title, c.url AS content_url, "
                f"{self._UNIT_SCORES_AGG} "
                f"FROM knowledge_units u JOIN creators cr ON cr.id=u.creator_id "
                f"JOIN contents c ON c.id=u.content_id WHERE u.id=%s", (unit_id,),
            ).fetchone()

    # --- 单元核查（站上意见 → 知识席位答复）与修改留痕 -----------------------

    REVIEW_CATEGORIES = ("quote", "grade", "scoring", "asset", "statement", "other")
    REVIEW_STATUSES = ("open", "answered", "closed")
    REVIEW_OUTCOMES = ("fixed", "no_change", "needs_info")
    REVIEW_BODY_MAX = 4000
    # 改了这些字段，已落库的评分就对不上单元了——评分器只认提取时冻结的 spec
    _SCORING_FIELDS = ("verifiability", "scoring_spec", "asset_symbol", "direction",
                       "magnitude", "horizon", "condition_text", "condition_observable")

    def _clean_body(self, body: str) -> str:
        body = (body or "").strip()
        if not body:
            raise ValueError("内容不能为空")
        if len(body) > self.REVIEW_BODY_MAX:
            raise ValueError(f"内容超过 {self.REVIEW_BODY_MAX} 字")
        return body

    @staticmethod
    def _lock_review(conn, review_id: int) -> dict:
        row = conn.execute("SELECT id, unit_id, status FROM unit_reviews WHERE id=%s FOR UPDATE",
                           (review_id,)).fetchone()
        if row is None:
            raise LookupError(f"核查 {review_id} 不存在")
        return row

    def create_review(self, unit_id: int, *, category: str, body: str, author: str) -> dict:
        """站上用户对一条单元提出核查意见。返回 review_detail。"""
        if category not in self.REVIEW_CATEGORIES:
            raise ValueError(f"category 须为 {'/'.join(self.REVIEW_CATEGORIES)}")
        body = self._clean_body(body)
        with self.pool.connection() as conn:
            if conn.execute("SELECT 1 FROM knowledge_units WHERE id=%s", (unit_id,)).fetchone() is None:
                raise LookupError(f"单元 {unit_id} 不存在")
            rid = conn.execute(
                "INSERT INTO unit_reviews(unit_id, category, created_by) VALUES (%s,%s,%s) RETURNING id",
                (unit_id, category, author)).fetchone()["id"]
            conn.execute("INSERT INTO unit_review_messages(review_id, role, author, body) "
                         "VALUES (%s,'reviewer',%s,%s)", (rid, author, body))
        return self.review_detail(rid)

    def add_review_message(self, review_id: int, *, body: str, author: str) -> dict:
        """站上用户在核查里补充说明、或回复知识席位的答复。已答复/已关闭的会重新打开。"""
        body = self._clean_body(body)
        with self.pool.connection() as conn:
            self._lock_review(conn, review_id)
            conn.execute("INSERT INTO unit_review_messages(review_id, role, author, body) "
                         "VALUES (%s,'reviewer',%s,%s)", (review_id, author, body))
            conn.execute("UPDATE unit_reviews SET status='open', closed_at=NULL, updated_at=now() "
                         "WHERE id=%s", (review_id,))
        return self.review_detail(review_id)

    def close_review(self, review_id: int) -> dict:
        """站上用户关闭核查（认可答复，或撤回）。之后再回复会重新打开。"""
        with self.pool.connection() as conn:
            if self._lock_review(conn, review_id)["status"] == "closed":
                raise ReviewConflict(f"核查 {review_id} 已经关闭")
            conn.execute("UPDATE unit_reviews SET status='closed', closed_at=now(), updated_at=now() "
                         "WHERE id=%s", (review_id,))
        return self.review_detail(review_id)

    def answer_review(self, review_id: int, *, body: str, outcome: str, author: str,
                      root_cause: str | None = None, sweep: str | None = None,
                      followup: str | None = None) -> dict:
        """知识席位答复一条待处理的核查。只由 CLI 调用，不开 HTTP。

        outcome=fixed 有两道闸：必须先有挂在这条核查下的修改记录（说改了就得真改了），
        root_cause 与 sweep 必须写（为什么会错、同类单元查了哪些）——否则等于只修了
        用户恰好看见的那一条。
        """
        if outcome not in self.REVIEW_OUTCOMES:
            raise ValueError(f"outcome 须为 {'/'.join(self.REVIEW_OUTCOMES)}")
        body = self._clean_body(body)
        root_cause, sweep, followup = ((x or "").strip() or None for x in (root_cause, sweep, followup))
        if outcome == "fixed" and not (root_cause and sweep):
            raise ValueError("outcome=fixed 时必须写 root_cause（为什么会错）"
                             "与 sweep（同类单元查了哪些、结果如何）")
        with self.pool.connection() as conn:
            row = self._lock_review(conn, review_id)
            if row["status"] != "open":
                raise ReviewConflict(f"核查 {review_id} 当前是 {row['status']}，只能答复 open 的")
            if outcome == "fixed" and conn.execute(
                    "SELECT 1 FROM unit_amendments WHERE review_id=%s", (review_id,)).fetchone() is None:
                raise ReviewConflict("outcome=fixed，但这条核查下没有修改记录——"
                                     "先用 amend 改单元并挂上 --review")
            conn.execute(
                "INSERT INTO unit_review_messages(review_id, role, author, body, resolution) "
                "VALUES (%s,'extractor',%s,%s,%s)",
                (review_id, author, body, Json({"outcome": outcome, "root_cause": root_cause,
                                                "sweep": sweep, "followup": followup})))
            conn.execute("UPDATE unit_reviews SET status='answered', updated_at=now() WHERE id=%s",
                         (review_id,))
        return self.review_detail(review_id)

    def review_detail(self, review_id: int) -> dict | None:
        """一条核查：本体 + 对话（按时间）+ 挂在它下面的修改记录（带改动字段清单）。"""
        with self.pool.connection() as conn:
            r = conn.execute("SELECT * FROM unit_reviews WHERE id=%s", (review_id,)).fetchone()
            if r is None:
                return None
            r["messages"] = conn.execute(
                "SELECT id, role, author, body, resolution, created_at FROM unit_review_messages "
                "WHERE review_id=%s ORDER BY id", (review_id,)).fetchall()
            r["amendments"] = conn.execute(
                "SELECT id, unit_id, before, after, reason, author, created_at FROM unit_amendments "
                "WHERE review_id=%s ORDER BY id", (review_id,)).fetchall()
        for a in r["amendments"]:
            a["changed"] = amendment_changes(a["before"], a["after"])
        return r

    def reviews_for_unit(self, unit_id: int) -> list[dict]:
        """单元详情里的核查面板：该单元的全部核查，新的在前。"""
        with self.pool.connection() as conn:
            ids = [row["id"] for row in conn.execute(
                "SELECT id FROM unit_reviews WHERE unit_id=%s ORDER BY id DESC", (unit_id,)).fetchall()]
        return [self.review_detail(i) for i in ids]

    def list_reviews(self, *, status: str | None = None, limit: int = 100) -> list[dict]:
        """核查队列：open 是知识席位的待办，answered 是用户的待确认。带单元摘要，不带对话全文。"""
        if status is not None and status not in self.REVIEW_STATUSES:
            raise ValueError(f"status 须为 {'/'.join(self.REVIEW_STATUSES)}")
        where, params = ("WHERE r.status=%s", (status,)) if status else ("", ())
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT r.*, u.kind, u.content_id, left(u.quote, 80) AS quote, "
                "u.payload->>'verifiability' AS verifiability, cr.name AS creator, "
                "(SELECT count(*) FROM unit_review_messages m WHERE m.review_id=r.id) AS n_messages, "
                "(SELECT left(m.body, 120) FROM unit_review_messages m WHERE m.review_id=r.id "
                " ORDER BY m.id DESC LIMIT 1) AS last_message "
                "FROM unit_reviews r JOIN knowledge_units u ON u.id=r.unit_id "
                f"JOIN creators cr ON cr.id=u.creator_id {where} "
                "ORDER BY r.updated_at DESC LIMIT %s", (*params, limit)).fetchall()

    def amend_unit(self, unit_id: int, *, reason: str, author: str, quote: str | None = None,
                   payload: dict | None = None, tags: list[str] | None = None,
                   review_id: int | None = None) -> dict:
        """原地修改一条单元并留痕（改前 / 改后 / 原因）。返回修改记录。

        与导入同一套闸门：pydantic 重验载荷、quote 须逐字出自原文。已有评分记录的单元
        不许改评分相关字段——历史评分会对不上单元；真要改评分语义，升 extractor_version 重提。
        """
        reason = (reason or "").strip()
        if not reason:
            raise ValueError("reason 不能为空")
        if quote is None and payload is None and tags is None:
            raise ValueError("没有要改的字段")
        with self.pool.connection() as conn:
            u = conn.execute(
                "SELECT u.kind, u.quote, u.locator, u.payload, u.tags, c.raw FROM knowledge_units u "
                "JOIN contents c ON c.id=u.content_id WHERE u.id=%s FOR UPDATE OF u", (unit_id,)).fetchone()
            if u is None:
                raise LookupError(f"单元 {unit_id} 不存在")
            if review_id is not None and conn.execute(
                    "SELECT 1 FROM unit_reviews WHERE id=%s AND unit_id=%s",
                    (review_id, unit_id)).fetchone() is None:
                raise ValueError(f"核查 {review_id} 不是针对单元 {unit_id} 的")
            new = KnowledgeUnit(kind=u["kind"], locator=u["locator"],
                                quote=u["quote"] if quote is None else quote,
                                payload=u["payload"] if payload is None else payload,
                                tags=u["tags"] if tags is None else tags)
            if not quote_in_source(u["raw"], new.quote):
                raise ValueError("quote 不在原文中（空白归一后须是子串）")
            before = {"quote": u["quote"], "payload": u["payload"], "tags": u["tags"]}
            after = {"quote": new.quote, "payload": new.payload, "tags": new.tags}
            if before == after:
                raise ValueError("改后与改前完全相同")
            # 旧载荷也过一遍模型再比，否则模型补的默认字段（如 benchmark: null）会被误判成改动
            try:
                old_payload = KnowledgeUnit(kind=u["kind"], quote=u["quote"], payload=u["payload"]).payload
            except ValueError:
                old_payload = u["payload"]
            touched = [f for f in self._SCORING_FIELDS if old_payload.get(f) != new.payload.get(f)]
            # 作废过的也算评过：否则先作废、再改判据，就成了看过结果再改答案
            if touched and conn.execute(
                    "SELECT 1 FROM claim_scores WHERE unit_id=%s "
                    "UNION ALL SELECT 1 FROM claim_score_voids WHERE unit_id=%s LIMIT 1",
                    (unit_id, unit_id)).fetchone():
                raise ReviewConflict(f"单元 {unit_id} 已有评分记录，不能改评分相关字段 {touched}；"
                                     "要改评分语义请升 extractor_version 重提")
            conn.execute("UPDATE knowledge_units SET quote=%s, payload=%s, tags=%s WHERE id=%s",
                         (new.quote, Json(new.payload), new.tags, unit_id))
            row = conn.execute(
                "INSERT INTO unit_amendments(unit_id, review_id, before, after, reason, author) "
                "VALUES (%s,%s,%s,%s,%s,%s) RETURNING *",
                (unit_id, review_id, Json(before), Json(after), reason, author)).fetchone()
        row["changed"] = amendment_changes(row["before"], row["after"])
        return row

    def void_score(self, unit_id: int, horizon_label: str, *, reason: str, author: str,
                   rescore: bool = False) -> dict:
        """作废一个评分时点：整行搬进 claim_score_voids（原样保留），从 claim_scores 移走。

        默认用于本不该存在的评分时点，作废后评分器不会再评它。`rescore=True` 用于评分器没按冻结的
        success_def 执行（机器配置漏了条件等）：配置修好后下一次运行重评。两者都不是改判据——
        判据写错要改单元并留痕，且评过分的单元评分字段是锁定的。
        """
        reason = (reason or "").strip()
        if not reason:
            raise ValueError("reason 不能为空")
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT * FROM claim_scores WHERE unit_id=%s AND horizon_label=%s FOR UPDATE",
                (unit_id, horizon_label)).fetchall()
            if not rows:
                raise LookupError(f"单元 {unit_id} 在 {horizon_label} 没有评分记录")
            out = None
            for r in rows:
                snapshot = {k: (v.isoformat() if hasattr(v, "isoformat") else v) for k, v in r.items()}
                out = conn.execute(
                    "INSERT INTO claim_score_voids(unit_id, horizon_label, scorer_version, score, reason, "
                    "author, rescore) VALUES (%s,%s,%s,%s,%s,%s,%s) RETURNING *",
                    (unit_id, horizon_label, r["scorer_version"], Json(snapshot), reason, author,
                     rescore)).fetchone()
                conn.execute("DELETE FROM claim_scores WHERE id=%s", (r["id"],))
        return out

    def score_voids(self, unit_id: int) -> list[dict]:
        with self.pool.connection() as conn:
            return conn.execute("SELECT * FROM claim_score_voids WHERE unit_id=%s ORDER BY id",
                                (unit_id,)).fetchall()

    def recent_scores(self, *, days: int = 14, limit: int = 100) -> list[dict]:
        """新到期评分流（今日页）：按评分落库时刻倒序，带单元与信源摘要。"""
        with self.pool.connection() as conn:
            return conn.execute(
                "SELECT s.id, s.unit_id, s.horizon_label, s.outcome, s.realized, "
                "s.eval_ts, s.created_at AS scored_at, "
                "u.kind, u.quote, u.payload, u.published_at, u.creator_id, u.content_id, "
                "cr.name AS creator, c.title AS content_title "
                f"FROM claim_scores s JOIN knowledge_units u ON u.id=s.unit_id "
                f"JOIN creators cr ON cr.id=u.creator_id JOIN contents c ON c.id=u.content_id "
                f"WHERE s.created_at >= now() - make_interval(days => %s) AND {ACTIVE_RUN} "
                f"ORDER BY s.created_at DESC, s.id DESC LIMIT %s", (days, limit),
            ).fetchall()

    def verification_queue(self, *, days: int = 14, limit: int = 120) -> dict:
        """验证中心的行动队列。

        评分行只代表已发生的判定；即将到期的 Claim 需从冻结的 eval_ladder
        反查，不能把“尚未写入评分”误报成没有工作。这是纯读取视图，不改变
        评分器或任何状态。
        """
        with self.pool.connection() as conn:
            due = conn.execute(f"""
                SELECT u.id AS unit_id, u.quote, u.payload, u.published_at,
                  u.ref_price_at_publish, cr.name AS creator, c.title AS content_title,
                  ladder.label AS horizon_label
                FROM knowledge_units u
                JOIN creators cr ON cr.id=u.creator_id
                JOIN contents c ON c.id=u.content_id
                CROSS JOIN LATERAL jsonb_array_elements_text(
                  COALESCE(u.payload->'scoring_spec'->'eval_ladder', '[]'::jsonb)
                ) AS ladder(label)
                WHERE u.kind='claim' AND {ACTIVE_RUN}
                  AND ladder.label ~ '^\\d{{4}}-\\d{{2}}-\\d{{2}}$'
                  AND ladder.label::date BETWEEN current_date AND current_date + %s
                  AND NOT EXISTS (
                    SELECT 1 FROM claim_scores s
                    WHERE s.unit_id=u.id AND s.horizon_label=ladder.label
                  )
                ORDER BY ladder.label, u.published_at DESC NULLS LAST
                LIMIT %s
            """, (days, limit)).fetchall()
            scores = conn.execute(f"""
                SELECT s.id AS score_id, s.unit_id, s.horizon_label, s.outcome, s.realized,
                  s.eval_ts, s.created_at AS scored_at, u.quote, u.payload, u.published_at,
                  u.ref_price_at_publish, cr.name AS creator, c.title AS content_title
                FROM claim_scores s
                JOIN knowledge_units u ON u.id=s.unit_id
                JOIN creators cr ON cr.id=u.creator_id
                JOIN contents c ON c.id=u.content_id
                WHERE {ACTIVE_RUN}
                ORDER BY s.created_at DESC, s.id DESC
                LIMIT %s
            """, (limit,)).fetchall()

        verdicts = [s for s in scores if s["outcome"] in {"hit", "partial", "miss"}]
        unavailable = [s for s in scores if s["outcome"] in {
            "unpriceable", "condition_unverifiable",
        }]
        review = [s for s in scores if s["outcome"] in {"condition_not_met", "pending"}]
        return {
            "overview": {
                "due": len(due), "completed": len(verdicts), "unavailable": len(unavailable),
                "review": len(review),
            },
            "due": due,
            "recent": verdicts,
            "unavailable": unavailable,
            "review": review,
        }

    def verification_detail(self, score_id: int) -> dict | None:
        """一次已落库验证的不可变判定档案，含出处和受影响的知识节点。"""
        with self.pool.connection() as conn:
            row = conn.execute("""
                SELECT s.id AS score_id, s.unit_id, s.horizon_label, s.outcome, s.realized,
                  s.eval_ts, s.created_at AS scored_at, s.scorer_version,
                  u.quote, u.locator, u.payload, u.tags, u.published_at,
                  u.ref_price_at_publish, u.extractor_version,
                  cr.id AS creator_id, cr.name AS creator,
                  c.id AS content_id, c.title AS content_title, c.url AS content_url
                FROM claim_scores s
                JOIN knowledge_units u ON u.id=s.unit_id
                JOIN creators cr ON cr.id=u.creator_id
                JOIN contents c ON c.id=u.content_id
                WHERE s.id=%s
            """, (score_id,)).fetchone()
            if row is None:
                return None
            row["nodes"] = conn.execute("""
                SELECT n.id, n.title, n.status, n.kind, a.relation, a.note
                FROM node_attestations a JOIN knowledge_nodes n ON n.id=a.node_id
                WHERE a.unit_id=%s ORDER BY n.id
            """, (row["unit_id"],)).fetchall()
        return row

    def units(self, *, kind: str | None = None, creator_id: int | None = None,
              limit: int = 100) -> list[dict]:
        cond, params = [ACTIVE_RUN], []
        if kind:
            cond.append("u.kind=%s")
            params.append(kind)
        if creator_id:
            cond.append("u.creator_id=%s")
            params.append(creator_id)
        where = "WHERE " + " AND ".join(cond)
        with self.pool.connection() as conn:
            return conn.execute(
                f"SELECT u.* FROM knowledge_units u {where} "
                f"ORDER BY u.published_at DESC NULLS LAST LIMIT %s", (*params, limit),
            ).fetchall()
